In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
K = 50
D = 9
L = 4

# ! Hybrid model
n_hidden_variables = 0
L_t = L - n_hidden_variables
L_w = n_hidden_variables

gllim = lib.GLLiM(K, D, L, gamma_type='full', sigma_type='diag', n_hidden_variables=n_hidden_variables)
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

(50, 4, 4)


In [3]:
lib._GLLiM_full_diag(K, D, L, 'full', 'full', n_hidden_variables)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(K,D,L, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00764633 0.00803163 0.00791868 ... 0.00784891 0.00754744 0.0077891 ]
  [0.0080215  0.00765251 0.00795056 ... 0.00765879 0.0078368  0.00785242]
  [0.00831832 0.00815417 0.00792513 ... 0.00780016 0.00811353 0.00821906]
  ...
  [0.00797886 0.00788521 0.00761182 ... 0.00824055 0.00768476 0.00759485]
  [0.00821362 0.00750835 0.00770521 ... 0.00773102 0.00816381 0.00789776]
  [0.00768191 0.00793804 0.00773084 ... 0.00779602 0.00815042 0.00760407]]

 [[0.00753985 0.00803309 0.0080398  ... 0.00776191 0.00749875 0.00794806]
  [0.00790979 0.0076539  0.00807216 ... 0.00757389 0.00778624 0.00801267]
  [0.00820248 0.00815565 0.00804635 ... 0.00771369 0.00806119 0.00838679]
  ...
  [0.00786775 0.00788664 0.00772824 ... 0.00814921 0.0076351

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.62082682 0.72667455 0.711019   0.8264092  0.02548601 0.64127049]
 [0.42380196 0.31143333 0.76627278 0.66345476 0.56833504 0.84055296]
 [0.97929688 0.60575065 0.38775367 0.10911108 0.72028435 0.65749815]
 [0.36489303 0.72992507 0.9191226  0.65349011 0.08013702 0.39973127]]
INFO: Alter theta covariance
INFO: Construct the GMM of the forward conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[13.16645607 13.16645607 13.16645607 13.16645607 13.16645607 13.16645607
  13.16645607 13.16645607 13.16645607]
 [13.12135079 13.12135079 13.12135079 13.12135079 13.12135079 13.12135079
  13.12135079 13.12135079 13.12135079]
 [14.35250413 14.35250413 14.35250413 14.35250413 14.35250413 14.35250413
  14.35250413 14.35250413 14.35250413]
 [12.75739545 12.75739545 12.75739545 12.75739545 12.75739545 12.75739545
  12.75739545 12.75739545 12.75739545]
 [10.18272728 10.18272728 10.18272728 10.18272728 10.18272728 10.18272728
  10.18272728 10.18272728 10.18272728]
 [13.61715861 13.61715861 13.61715861 13.61715861 13.61715861 13.61715861
  13.61715861 13.61715861 13.61715861]]
[[[1.03865617e+00 1.91977190e-26 1.91977190e-26 1.91977190e-26
   1.91977190e-26 1.91977190e-26 1.91977190e-26 1.91977190e-26
   1.91977190e-26]
  [1.91977190e-26 1.08977684e+00 1.91977190e-26 1.91977190e-26
   1.91977190e-26 1.91977190e-26 1.91977190e-26 1.91977190e-26
   1.91977190e-26]
  [1.91977190e-26 1.91977190e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
Time One inversion = 0.010573387145996094


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta

In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.15506846 0.2140174  0.20911181 0.22165386]
 [0.14045879 0.20591973 0.19494732 0.21507369]
 [0.1438272  0.21367558 0.18950524 0.21400535]
 [0.15098214 0.21391012 0.20720789 0.22375716]
 [0.14623858 0.20532963 0.20740126 0.219908  ]
 [0.16540479 0.23340958 0.20472473 0.2284169 ]
 [0.14315396 0.20658825 0.1954098  0.21264322]
 [0.14022966 0.20694381 0.18528851 0.20688573]
 [0.15098363 0.22115233 0.19200252 0.21758708]
 [0.13757847 0.20550394 0.1859888  0.20900892]
 [0.15166103 0.22177554 0.20294068 0.22796036]
 [0.146199   0.2125746  0.19057388 0.21133943]
 [0.14592472 0.21655771 0.19047036 0.21649257]
 [0.15920425 0.22503874 0.20582031 0.22665093]
 [0.14792716 0.21461282 0.19206547 0.21396967]
 [0.14183732 0.21161633 0.18732524 0.21245019]
 [0.14061155 0.2095818  0.18684106 0.21071139]
 [0.14775187 0.21493471 0.19268511 0.21487504]
 [0.1442085  0.20949092 0.19161358 0.21108243]
 [0.14634682 0.20913307 0.19310879 0.21025755]
 [0.15876626 0.22495845 0.20254434 0.2243834 ]
 [0.137

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model


Generating dataset
Initializing GLLIM model


INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.672556, Best log likelihood : 25.672556
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.854188
INFO:root:Iteration : 2, log likelihood : 26.039040
INFO:root:Iteration : 3, log likelihood : 26.137893


Training model


INFO:root:Iteration : 4, log likelihood : 26.239464
INFO:root:Iteration : 5, log likelihood : 26.319723
INFO:root:Iteration : 6, log likelihood : 26.371244
INFO:root:Iteration : 7, log likelihood : 26.415345
INFO:root:Iteration : 8, log likelihood : 26.437270
INFO:root:Iteration : 9, log likelihood : 26.460223
INFO:root:Iteration : 10, log likelihood : 26.480025
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(K,D,L, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01509958 0.0099161  0.01855557 0.0180158  0.01696352 0.00799923
 0.01193843 0.00799066 0.01699108 0.01300311 0.01893037 0.01299326
 0.03208216 0.02949064 0.02309675 0.02453204 0.05658438 0.02294447
 0.01603225 0.01812234 0.01005206 0.00994309 0.01705424 0.02000116
 0.01204576 0.02230719 0.01996091 0.01345687 0.02637247 0.01679198
 0.00993518 0.02854347 0.03978654 0.01257861 0.02958797 0.01098956
 0.02400972 0.03450241 0.01832807 0.01002463 0.0179494  0.01215935
 0.02274675 0.02791784 0.01499705 0.01500195 0.02789436 0.03097173
 0.01998245 0.03282551]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
0.9999999999999999


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(K,D,L, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
L_t = L
full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00313806 0.00235701 0.0022914  0.00184815 0.00261933 0.00281535]
  [0.00235701 0.00254663 0.00183073 0.00174613 0.00224876 0.00209672]
  [0.0022914  0.00183073 0.00226517 0.00173562 0.00219838 0.00242333]
  [0.00184815 0.00174613 0.00173562 0.00224181 0.00235127 0.00197837]
  [0.00261933 0.00224876 0.00219838 0.00235127 0.00301538 0.00274832]
  [0.00281535 0.00209672 0.00242333 0.00197837 0.00274832 0.00298195]]

 [[0.00114683 0.00120653 0.00117105 0.0011878  0.0008999  0.00117265]
  [0.00120653 0.00222392 0.00137157 0.00177809 0.0015126  0.00190146]
  [0.00117105 0.00137157 0.0022176  0.00130186 0.00120217 0.00163035]
  [0.0011878  0.00177809 0.00130186 0.00165473 0.00127621 0.00162519]
  [0.0008999  0.0015126  0.00120217 0.00127621 0.00128064 0.00170338]
  [0.00117265 0.00190146 0.00163035 0.00162519 0.00170338 0.0023255 ]]

 [[0.00237579 0.00159579 0.00175917 0.00240125 0.00216493 0.00217465]
  [0.00159579 0.00128903 0.00136909 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.993882
INFO: Iteration : 2, log likelihood : 2.993978
INFO: Iteration : 3, log likelihood : 2.990671
INFO: Iteration : 4, log likelihood : 2.990156
INFO: Iteration : 5, log likelihood : 2.990052
INFO: Iteration : 6, log likelihood : 2.990052
INFO: Iteration : 7, log likelihood : 2.990052
INFO: Iteration : 8, log likelihood : 2.990052
INFO: Iteration : 9, log likelihood : 2.990052
INFO: Iteration : 10, log likelihood : 2.990052
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.990052, Best log likelihood : 2.990052
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 0.43538893  0.99277675  2.05961006  0.23947877  0.56293856]
 [ 1.35352225  0.88096677 -1.21655722  0.7077363   0.74197524]
 [ 1.02485396  0.64724984 -0.31752554 -0.13909351  0.04594341]
 [-0.43421235  0.58454263  2.56380211  0.63669867 -0.02187817]
 [ 0.22740624  1.6676176   1.41486323  0.70122569  0.54129673]
 [ 0.6205445   0.12733403  2.01020248  0.75728952  0.89359432]
 [ 0.18333273 -0.56928066  0.83405719  0.4091162   0.74268477]
 [-0.40813967 -0.00438252  0.46181135  0.51286569  0.58986838]
 [-0.45666645  1.61310905  0.25286408  0.90726666  0.58075467]
 [-0.16561207  0.10840357  0.70435327 -0.14687337  1.09326404]
 [ 1.81286244  0.95344235  2.06237618  1.11184759  0.51857665]
 [ 0.49278678  0.50189609  1.85513092  0.00620383  0.51115559]
 [-1.40588118  0.2644309   1.17169771  0.51483963  0.070445  ]
 [-0.80154876  0.90766955  1.00500685  0.62363618  0.69825835]
 [-1.40653743  0.73113046 -0.2122992   0.6487102   0.36491533]
 [ 1.26324866  0.81559359  0.69003448  0.16653011  0.24

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.993882
INFO: Iteration : 2, log likelihood : 2.993978
INFO: Iteration : 3, log likelihood : 2.990671
INFO: Iteration : 4, log likelihood : 2.990156
INFO: Iteration : 5, log likelihood : 2.990052
INFO: Iteration : 6, log likelihood : 2.990052
INFO: Iteration : 7, log likelihood : 2.990052
INFO: Iteration : 8, log likelihood : 2.990052
INFO: Iteration : 9, log likelihood : 2.990052
INFO: Iteration : 10, log likelihood : 2.990052
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.990052, Best log

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(K,D,L, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00263986 0.00147079 0.00220288 0.00303448 0.00252833 0.00171132]
  [0.00147079 0.00114923 0.00078724 0.00158369 0.00133678 0.00081111]
  [0.00220288 0.00078724 0.0032669  0.00288318 0.00209896 0.0024763 ]
  [0.00303448 0.00158369 0.00288318 0.00417898 0.00290489 0.00273215]
  [0.00252833 0.00133678 0.00209896 0.00290489 0.00245642 0.00154972]
  [0.00171132 0.00081111 0.0024763  0.00273215 0.00154972 0.00250139]]

 [[0.00174612 0.00076984 0.00219547 0.00092602 0.0015607  0.00121973]
  [0.00076984 0.00147928 0.00148285 0.0008109  0.00115024 0.00186533]
  [0.00219547 0.00148285 0.00342506 0.00160467 0.00275388 0.00253534]
  [0.00092602 0.0008109  0.00160467 0.00090473 0.00149202 0.00143003]
  [0.0015607  0.00115024 0.00275388 0.00149202 0.00291482 0.00230383]
  [0.00121973 0.00186533 0.00253534 0.00143003 0.00230383 0.0028257 ]]

 [[0.00225684 0.00194179 0.0015178  0.00202946 0.00162674 0.00160955]
  [0.00194179 0.00243213 0.00170855 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.228726
INFO: Iteration : 2, log likelihood : -0.228736
INFO: Iteration : 3, log likelihood : -0.228737
INFO: Iteration : 4, log likelihood : -0.228737
INFO: Iteration : 5, log likelihood : -0.228737
INFO: Iteration : 6, log likelihood : -0.228737
INFO: Iteration : 7, log likelihood : -0.228737
INFO: Iteration : 8, log likelihood : -0.228737
INFO: Iteration : 9, log likelihood : -0.228737
INFO: Iteration : 10, log likelihood : -0.228737
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.228737, Best log likelihood : -0.228737
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM m

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[0.19995651 0.19290959 0.19489398 0.23103983 0.1812001 ]]
[[0.19995651 0.19290959 0.19489398 0.23103983 0.1812001 ]]


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.228726
INFO: Iteration : 2, log likelihood : -0.228736
INFO: Iteration : 3, log likelihood : -0.228737
INFO: Iteration : 4, log likelihood : -0.228737
INFO: Iteration : 5, log likelihood : -0.228737
INFO: Iteration : 6, log likelihood : -0.228737
INFO: Iteration : 7, log likelihood : -0.228737
INFO: Iteration : 8, log likelihood : -0.228737
INFO: Iteration : 9, log likelihood : -0.228737
INFO: Iteration : 10, log likelihood : -0.228737
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.22873

In [36]:
import os
import newkernelo as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -2.554492
INFO: Iteration : 2, log likelihood : -2.554494
INFO: Iteration : 3, log likelihood : -2.554494
INFO: Iteration : 4, log likelihood : -2.554494
INFO: Iteration : 5, log likelihood : -2.554494
INFO: Iteration : 6, log likelihood : -2.554494
INFO: Iteration : 7, log likelihood : -2.554494
INFO: Iteration : 8, log likelihood : -2.554494
INFO: Iteration : 9, log lik

In [37]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
