In [23]:
# import newkernelo as lib
import xllim as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [24]:
K = 50
D = 9
L = 4

# ! Hybrid model
n_hidden_variables = 0
L_t = L - n_hidden_variables
L_w = n_hidden_variables

gllim = lib.GLLiM(K, D, L, gamma_type='full', sigma_type='diag', n_hidden_variables=n_hidden_variables)
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
print(gllim.getParamPi())
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'xllim._GLLiM_full_diag'>
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(50, 4, 4)
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [25]:
lib._GLLiM_full_diag(K, D, L, 'full', 'full', n_hidden_variables)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [27]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(50, 9, 4)
GLLiM dimensions are (L=4, D=9, K=50)


In [28]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [29]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
4
9
50


In [30]:
Pi = np.ones(K) * 1 / K
A = np.ones((K, D, L))
C = np.ones((K, L)) * 2
Gamma = np.ones((K, L, L)) * 0.2
B = np.ones((K, D)) * 3
Sigma = np.ones((K, D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:, :, 0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 ...

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  ...
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2

In [31]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [32]:
new_theta = lib.GLLiMParameters(K,D,L, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'xllim._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 ...

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 

In [33]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]4
9
50

[[[0.00790857 0.00769938 0.00813048 ... 0.00840009 0.00773098 0.00794762]
  [0.00765967 0.00745706 0.0078746  ... 0.00813572 0.00748767 0.00769749]
  [0.00791652 0.00770711 0.00813866 ... 0.00840853 0.00773875 0.0079556 ]
  [0.00775981 0.00755455 0.00797755 ... 0.00824208 0.00758556 0.00779812]]

 [[0.00828893 0.00762059 0.00825701 ... 0.00765793 0.00791187 0.00767145]
  [0.00837407 0.00769887 0.00834182 ... 0.00773659 0.00799314 0.00775024]
  [0.00827448 0.0076073  0.00824261 ... 0.00764457 0.00789808 0.00765807]
  [0.00827679 0.00760942 0.00824491 ... 0.00764671 0.00790028 0.00766021]]

 [[0.00808787 0.00754454 0.00797983 ... 0.00761484 0.00800778 0.00819598]
  [0.00798287 0.00744659 0.00787623 ... 0.00751598 0.00790382 0

In [34]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.68927109 0.61825396 0.5924001  0.0312583  0.13246174 0.67315515]
 [0.75911994 0.74436254 0.97626457 0.75072334 0.70742383 0.8105358 ]
 [0.46800013 0.95788725 0.29851262 0.69772068 0.93554467 0.61826256]
 [0.61031249 0.21769577 0.20783053 0.33811805 0.51496023 0.03584307]]
INFO: Alter theta covariance
INFO: Construct the GMM of the forward conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [35]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[13.58011096 13.58011096 13.58011096 13.58011096 13.58011096 13.58011096
  13.58011096 13.58011096 13.58011096]
 [13.61459856 13.61459856 13.61459856 13.61459856 13.61459856 13.61459856
  13.61459856 13.61459856 13.61459856]
 [12.22502345 12.22502345 12.22502345 12.22502345 12.22502345 12.22502345
  12.22502345 12.22502345 12.22502345]
 [11.45346111 11.45346111 11.45346111 11.45346111 11.45346111 11.45346111
  11.45346111 11.45346111 11.45346111]
 [12.87117138 12.87117138 12.87117138 12.87117138 12.87117138 12.87117138
  12.87117138 12.87117138 12.87117138]
 [12.41338976 12.41338976 12.41338976 12.41338976 12.41338976 12.41338976
  12.41338976 12.41338976 12.41338976]]
[[[1.05567134e+00 4.93038066e-26 4.93038066e-26 4.93038066e-26
   4.93038066e-26 4.93038066e-26 4.93038066e-26 4.93038066e-26
   4.93038066e-26]
  [4.93038066e-26 1.02892362e+00 4.93038066e-26 4.93038066e-26
   4.93038066e-26 4.93038066e-26 4.93038066e-26 4.93038066e-26
   4.93038066e-26]
  [4.93038066e-26 4.93038066e-2

In [36]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.0031173229217529297
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [37]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [38]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means iTime Multi inversion = 0.012633323669433594
n the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO

In [39]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.18798416 0.18066736 0.189966   0.17362177]
 [0.19511505 0.18590626 0.19450224 0.18154252]
 [0.1869019  0.17641283 0.18457413 0.1738047 ]
 [0.18539508 0.17526809 0.1835643  0.17214609]
 [0.20285854 0.19350512 0.20202486 0.18937904]
 [0.19491158 0.1850065  0.19335273 0.18161691]
 [0.19198175 0.18278122 0.19138997 0.1783917 ]
 [0.20017663 0.19358661 0.20310845 0.18557856]
 [0.19361633 0.18709093 0.19665654 0.17896262]
 [0.19909605 0.19002082 0.19865238 0.18548809]
 [0.20280413 0.19525736 0.20442694 0.18860104]
 [0.17884455 0.17066539 0.17968254 0.16478597]
 [0.18018179 0.17100201 0.17965515 0.1665299 ]
 [0.19407042 0.18575466 0.19467503 0.18013559]
 [0.20778734 0.19837377 0.20685645 0.19435428]
 [0.19443081 0.18577626 0.19457368 0.18063327]
 [0.20122114 0.19295146 0.20186603 0.1873003 ]
 [0.19542327 0.18648814 0.19518157 0.18174257]
 [0.18038606 0.17121072 0.17986483 0.16673332]
 [0.19783276 0.18717496 0.19524138 0.1848527 ]
 [0.19572491 0.18588223 0.19424836 0.18240893]
 [0.199

# GLLiM TRAIN

In [40]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [41]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model


Generating dataset
Initializing GLLIM model


INFO:root:	Current log likelihood : 25.669889, Best log likelihood : 25.669889
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.848586
INFO:root:Iteration : 2, log likelihood : 26.046118


Training model


INFO:root:Iteration : 3, log likelihood : 26.152046
INFO:root:Iteration : 4, log likelihood : 26.252199
INFO:root:Iteration : 5, log likelihood : 26.330696
INFO:root:Iteration : 6, log likelihood : 26.387124
INFO:root:Iteration : 7, log likelihood : 26.420060
INFO:root:Iteration : 8, log likelihood : 26.441249
INFO:root:Iteration : 9, log likelihood : 26.460856
INFO:root:Iteration : 10, log likelihood : 26.477541
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [42]:
theta_0 = lib.GLLiMParameters(K,D,L, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

# print(np.array(gllim_parameters_0.Pi))
# print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
# print(np.array(gllim_parameters_0.C).shape)
# print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
# print(np.array(gllim_parameters_0.B).shape)
# print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.array(gllim_parameters_0.A))
theta_0.C = np.copy(np.array(gllim_parameters_0.C.T))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B.T))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
1.0


In [43]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [44]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [45]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [48]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(K, D, L, "full", "full")

Gamma = np.random.rand(K, L, L)
Sigma = np.random.rand(K, D, D)
for k in range(K):
    Gamma[k, :, :] += np.eye(L) * 0.1
    Gamma[k, :, :] = np.dot(Gamma[k, :, :], Gamma[k, :, :].T) * 0.001
    Sigma[k, :, :] += np.eye(D) * 0.1
    Sigma[k, :, :] = np.dot(Sigma[k, :, :], Sigma[k, :, :].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((K, D, L)) * 0.3
theta_full.C = np.ones((K, L)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((K, D)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(
    L, N
)  # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D, N)

In [49]:
L_t = L
full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [50]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00136872 0.00080458 0.00137902 0.00146787 0.00092968 0.00162528]
  [0.00080458 0.00161767 0.00132311 0.00117099 0.00108433 0.00120041]
  [0.00137902 0.00132311 0.00254857 0.00268228 0.00179966 0.00172439]
  [0.00146787 0.00117099 0.00268228 0.00309152 0.00184864 0.00204775]
  [0.00092968 0.00108433 0.00179966 0.00184864 0.00142822 0.00128057]
  [0.00162528 0.00120041 0.00172439 0.00204775 0.00128057 0.00237777]]

 [[0.00188191 0.00176992 0.00149967 0.0014322  0.00181624 0.00117565]
  [0.00176992 0.00203859 0.00185364 0.00134431 0.00202277 0.00127392]
  [0.00149967 0.00185364 0.00295206 0.00101934 0.00175333 0.00158036]
  [0.0014322  0.00134431 0.00101934 0.00139827 0.00187722 0.00117929]
  [0.00181624 0.00202277 0.00175333 0.00187722 0.00288543 0.00177273]
  [0.00117565 0.00127392 0.00158036 0.00117929 0.00177273 0.0015662 ]]

 [[0.00277916 0.00186761 0.00145496 0.00178466 0.00127399 0.00278917]
  [0.00186761 0.00149365 0.001066   0.

In [51]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.987134
INFO: Iteration : 2, log likelihood : 2.987067
INFO: Iteration : 3, log likelihood : 2.987067
INFO: Iteration : 4, log likelihood : 2.987067
INFO: Iteration : 5, log likelihood : 2.987067
INFO: Iteration : 6, log likelihood : 2.987067
INFO: Iteration : 7, log likelihood : 2.987067
INFO: Iteration : 8, log likelihood : 2.987067
INFO: Iteration : 9, log likelihood : 2.987067
INFO: Iteration : 10, log likelihood : 2.987067
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.987067, Best log likelihood : 2.987067
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	

In [52]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 0.14448511  0.48644452 -0.23762648  0.66166497  0.18754134  0.1679014
   0.83803477  0.23556446  0.91992785  1.29918097 -0.11345851  0.8154045
   0.01064019  0.58145571  0.53163069  0.41165141  0.56246632  0.59179359
   0.34371724 -0.0199803   0.28971467 -0.64420471  0.96455208  0.63626311
   1.00766281  0.93997437  0.99556272  0.27684006  1.07632258  0.39624816]
 [ 0.88782323  0.76256872  0.99999209  1.18901195  0.03236779  0.40886242
   0.33568858 -0.51701611  1.39125039  0.46375651  1.28816816  1.54421238
   0.21196517 -0.19258436  0.43395806  1.42707404  0.86833409  0.70050808
   0.47085937 -0.46290053  0.73291943  1.0247287  -0.1278563  -0.47112345
   1.66831485  1.2152032  -0.24721382  0.84194274 -0.64020279  0.29262115]
 [ 0.55773884  0.31068839  0.60251995  0.97496085  0.94649621  0.35262791
  -0.27142592  0.18498468  0.22228243  0.25470836  1.4581547  -0.58138642
  -0.02122594  1.31351067  0.31930253  0.94280026 -0.16047802  0.60513432
   0.84664955  0.51291353  0.87659083 

#### Initialize + train GLLiM full/full from scratch

In [53]:
new_full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.987134
INFO: Iteration : 2, log likelihood : 2.987067
INFO: Iteration : 3, log likelihood : 2.987067
INFO: Iteration : 4, log likelihood : 2.987067
INFO: Iteration : 5, log likelihood : 2.987067
INFO: Iteration : 6, log likelihood : 2.987067
INFO: Iteration : 7, log likelihood : 2.987067
INFO: Iteration : 8, log likelihood : 2.987067
INFO: Iteration : 9, log likelihood : 2.987067
INFO: Iteration : 10, log likelihood : 2.987067
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.987067, Best log

## GLLM training : EM estimator : full/diag

In [54]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(K, D, L, "full", "diag")

Gamma = np.random.rand(K, L, L)
Sigma = np.ones((K, D)) + np.random.rand(K, D) * 0.1
for k in range(K):
    Gamma[k, :, :] += np.eye(L) * 0.1
    Gamma[k, :, :] = np.dot(Gamma[k, :, :], Gamma[k, :, :].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(K, D, L) * 0.3
new_theta.C = np.random.rand(K, L) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(K, D) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L, N)
Y_gen = np.random.rand(D, N)

In [55]:
diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [56]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00104224 0.00075301 0.00142262 0.00154752 0.00160688 0.00145968]
  [0.00075301 0.00218639 0.00153115 0.0015469  0.00236279 0.00202829]
  [0.00142262 0.00153115 0.00275298 0.00269056 0.00230434 0.00233166]
  [0.00154752 0.0015469  0.00269056 0.00303653 0.00272029 0.00257745]
  [0.00160688 0.00236279 0.00230434 0.00272029 0.00367671 0.00314085]
  [0.00145968 0.00202829 0.00233166 0.00257745 0.00314085 0.00288505]]

 [[0.00265205 0.00156149 0.00189363 0.0022844  0.00177877 0.00215552]
  [0.00156149 0.00161964 0.00137844 0.00160857 0.00134166 0.00155407]
  [0.00189363 0.00137844 0.00252412 0.0023272  0.00168394 0.00183587]
  [0.0022844  0.00160857 0.0023272  0.00264349 0.0018919  0.00188887]
  [0.00177877 0.00134166 0.00168394 0.0018919  0.00185207 0.00144359]
  [0.00215552 0.00155407 0.00183587 0.00188887 0.00144359 0.00219465]]

 [[0.00190633 0.00151524 0.00164225 0.00130208 0.0012876  0.00113471]
  [0.00151524 0.00246199 0.00168471 0.

In [57]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.226472
INFO: Iteration : 2, log likelihood : -0.226481
INFO: Iteration : 3, log likelihood : -0.226481
INFO: Iteration : 4, log likelihood : -0.226481
INFO: Iteration : 5, log likelihood : -0.226481
INFO: Iteration : 6, log likelihood : -0.226481
INFO: Iteration : 7, log likelihood : -0.226481
INFO: Iteration : 8, log likelihood : -0.226481
INFO: Iteration : 9, log likelihood : -0.226481
INFO: Iteration : 10, log likelihood : -0.226481
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.226481, Best log likelihood : -0.226481
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM m

In [58]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[0.20811213 0.18162998 0.20030422 0.20497684 0.20497684]]
[[0.20811213 0.18162998 0.20030422 0.20497684 0.20497684]]


#### Initialize + train GLLiM full/diag from scratch

In [59]:
new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.226472
INFO: Iteration : 2, log likelihood : -0.226481
INFO: Iteration : 3, log likelihood : -0.226481
INFO: Iteration : 4, log likelihood : -0.226481
INFO: Iteration : 5, log likelihood : -0.226481
INFO: Iteration : 6, log likelihood : -0.226481
INFO: Iteration : 7, log likelihood : -0.226481
INFO: Iteration : 8, log likelihood : -0.226481
INFO: Iteration : 9, log likelihood : -0.226481
INFO: Iteration : 10, log likelihood : -0.226481
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.22648

In [61]:
import os
import xllim as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -2.544053
INFO: Iteration : 2, log likelihood : -2.544072
INFO: Iteration : 3, log likelihood : -2.544073
INFO: Iteration : 4, log likelihood : -2.544073
INFO: Iteration : 5, log likelihood : -2.544073
INFO: Iteration : 6, log likelihood : -2.544073
INFO: Iteration : 7, log likelihood : -2.544073
INFO: Iteration : 8, log likelihood : -2.544073
INFO: Iteration : 9, log lik

In [62]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
