In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

(50, 4, 4)


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00831883 0.00822851 0.00774953 ... 0.00737626 0.00821148 0.00782516]
  [0.00817766 0.00785973 0.00811317 ... 0.00807232 0.00823067 0.00832024]
  [0.00797192 0.00759102 0.00757254 ... 0.0079889  0.00763888 0.00804199]
  ...
  [0.00784665 0.00761618 0.00784415 ... 0.00781615 0.00774664 0.00769387]
  [0.00761368 0.00780796 0.00789526 ... 0.0079501  0.00837392 0.00810126]
  [0.00809182 0.00775975 0.00773338 ... 0.00801682 0.00808526 0.00778633]]

 [[0.00822587 0.00830913 0.00781859 ... 0.00744725 0.00804961 0.00764139]
  [0.00808628 0.00793674 0.00818546 ... 0.00815    0.00806842 0.00812485]
  [0.00788284 0.00766539 0.00764002 ... 0.00806578 0.0074883  0.00785313]
  ...
  [0.00775897 0.0076908  0.00791405 ... 0.00789137 0.0075939

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.76202126 0.44993988 0.76352014 0.96871134 0.41664696 0.00759993]
 [0.24608911 0.03471182 0.17703182 0.14960062 0.98506515 0.32849351]
 [0.74085694 0.26844144 0.8212428  0.38940967 0.54090839 0.12122257]
 [0.80347211 0.38992624 0.08214613 0.92265947 0.17484396 0.09390388]]
INFO: Alter theta covariance
INFO: Construct the GMM of the forward conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[13.65731827 13.65731827 13.65731827 13.65731827 13.65731827 13.65731827
  13.65731827 13.65731827 13.65731827]
 [ 9.42905813  9.42905813  9.42905813  9.42905813  9.42905813  9.42905813
   9.42905813  9.42905813  9.42905813]
 [11.53182266 11.53182266 11.53182266 11.53182266 11.53182266 11.53182266
  11.53182266 11.53182266 11.53182266]
 [13.29114328 13.29114328 13.29114328 13.29114328 13.29114328 13.29114328
  13.29114328 13.29114328 13.29114328]
 [12.35239338 12.35239338 12.35239338 12.35239338 12.35239338 12.35239338
  12.35239338 12.35239338 12.35239338]
 [ 7.65365965  7.65365965  7.65365965  7.65365965  7.65365965  7.65365965
   7.65365965  7.65365965  7.65365965]]
[[[1.05346005e+00 1.65474619e-25 1.65474619e-25 1.65474619e-25
   1.65474619e-25 1.65474619e-25 1.65474619e-25 1.65474619e-25
   1.65474619e-25]
  [1.65474619e-25 1.05696405e+00 1.65474619e-25 1.65474619e-25
   1.65474619e-25 1.65474619e-25 1.65474619e-25 1.65474619e-25
   1.65474619e-25]
  [1.65474619e-25 1.65474619e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
Time One inversion = 0.011085987091064453


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.038054704666137695
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO

In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.22468575 0.22449721 0.15416906 0.1396118 ]
 [0.22314143 0.2226375  0.15532054 0.14178628]
 [0.22367434 0.22148271 0.17045008 0.16242617]
 [0.2289341  0.22787781 0.16599753 0.15428924]
 [0.23202128 0.23080796 0.17050219 0.15931916]
 [0.22412929 0.22363714 0.15622514 0.14265628]
 [0.22686964 0.22621803 0.16039572 0.14735824]
 [0.23062981 0.23018316 0.16245663 0.14876542]
 [0.21817701 0.2183175  0.14469156 0.1290341 ]
 [0.22863812 0.22752936 0.1661497  0.15461156]
 [0.22855308 0.22808167 0.16055519 0.14693672]
 [0.23469846 0.23375279 0.17091587 0.15886964]
 [0.23478518 0.23419771 0.16790855 0.15469366]
 [0.23424966 0.23305788 0.17258692 0.16134254]
 [0.2236727  0.22291429 0.15806169 0.14536021]
 [0.23050713 0.22899741 0.17151899 0.16129671]
 [0.2346246  0.23460506 0.16283749 0.14776871]
 [0.23631993 0.23654619 0.16243972 0.14657518]
 [0.22922608 0.22866803 0.16198883 0.14865554]
 [0.23202894 0.23084071 0.17029203 0.15902681]
 [0.23491935 0.23418285 0.1693339  0.15660611]
 [0.213

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model


Generating dataset
Initializing GLLIM model


INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.694678, Best log likelihood : 25.694678
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.851236
INFO:root:Iteration : 2, log likelihood : 25.997592
INFO:root:Iteration : 3, log likelihood : 26.100855


Training model


INFO:root:Iteration : 4, log likelihood : 26.227028
INFO:root:Iteration : 5, log likelihood : 26.301207
INFO:root:Iteration : 6, log likelihood : 26.338886
INFO:root:Iteration : 7, log likelihood : 26.386568
INFO:root:Iteration : 8, log likelihood : 26.444440
INFO:root:Iteration : 9, log likelihood : 26.458157
INFO:root:Iteration : 10, log likelihood : 26.475342
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01483968 0.01019767 0.01700113 0.02276493 0.01599932 0.00799936
 0.00998516 0.00798408 0.01775292 0.01399971 0.01895863 0.01287389
 0.02609136 0.03007917 0.02296362 0.02477642 0.05270715 0.02297179
 0.0199581  0.01910847 0.01003383 0.0099527  0.01706636 0.02221954
 0.01244287 0.02238221 0.01895877 0.0132115  0.02828297 0.01599898
 0.01220929 0.03128414 0.04132713 0.01115435 0.03032741 0.01231438
 0.02401257 0.03328285 0.01915864 0.00987545 0.01795632 0.01214284
 0.02371302 0.02475468 0.01457522 0.01500267 0.02645504 0.0280478
 0.01997866 0.03286526]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00184858 0.00142339 0.00149795 0.00152359 0.00155535 0.00082741]
  [0.00142339 0.00193535 0.00177426 0.00143402 0.0020523  0.00140684]
  [0.00149795 0.00177426 0.00254942 0.00189906 0.0029668  0.00196039]
  [0.00152359 0.00143402 0.00189906 0.0022296  0.00231108 0.00169848]
  [0.00155535 0.0020523  0.0029668  0.00231108 0.00359717 0.00234303]
  [0.00082741 0.00140684 0.00196039 0.00169848 0.00234303 0.00237712]]

 [[0.00238324 0.00099549 0.00160038 0.00240538 0.00180258 0.00181711]
  [0.00099549 0.00083568 0.0009421  0.0009593  0.00124115 0.00098691]
  [0.00160038 0.0009421  0.00163786 0.0018992  0.00191583 0.00165408]
  [0.00240538 0.0009593  0.0018992  0.00272623 0.00203826 0.00200665]
  [0.00180258 0.00124115 0.00191583 0.00203826 0.00279113 0.0022952 ]
  [0.00181711 0.00098691 0.00165408 0.00200665 0.0022952  0.00213876]]

 [[0.0022479  0.00200086 0.00217355 0.00120271 0.00181304 0.00179658]
  [0.00200086 0.00221205 0.00213999 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : 0.149740                                                           
INFO: Iteration : 2, log likelihood : 0.149160                                                           
INFO: Iteration : 3, log likelihood : 0.149271                                                           
INFO: Iteration : 4, log likelihood : 0.149314                                                           
INFO: Iteration : 5, log likelihood : 0.149314                                                           
INFO: Iteration : 6, log likelihood : 0.149314                                                

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[-0.73654066  0.22733805  1.17242163  1.01179396  1.0911404 ]
 [ 0.08095072  1.06533718  1.53342636  0.94799833 -0.05632104]
 [ 0.81291152 -0.64409091  1.32823977  0.32710265  0.46854818]
 [ 0.59684912  0.85059585 -0.09441587  0.81232973  0.2920438 ]
 [-0.42411154  0.84127187  0.05447016  0.94763238  0.92577742]
 [-0.10214691  0.67166973 -0.45292575  0.36810293  0.79543026]
 [ 1.03028842  0.17301078  1.26772799  0.77664324  0.6945969 ]
 [ 0.60136568  0.56863268  0.15607696 -0.02469815  0.25827016]
 [ 0.34171167  0.16132243  0.98332679  0.65724358  0.6182181 ]
 [-0.66394577  0.3975414  -0.12658488  0.37216649  0.98771831]
 [-0.43985539  0.52359299  1.50553034  0.48010318  1.04403341]
 [ 0.10822633  0.85333069  0.3508784   1.02415647  0.61029331]
 [ 0.95895108  0.26855229  0.69014013  0.63326081 -0.2290444 ]
 [-0.1347042   0.5645419   0.22899111  0.56155801  0.20592037]
 [ 0.84463152 -0.12054839 -0.36617216  0.90597798 -0.00535448]
 [ 0.34058958  0.91389302  0.09103048  0.5053577   0.05

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.

INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : 0.149740                                                           
INFO: Iteration : 2, log likelihood : 0.149160                                                           
INFO: Iteration : 3, log likelihood : 0.149271                                                           
INFO: Iteration : 4, log likelihood : 0.149314                                                           
INFO: Iteration : 5, log likelihood : 0.149314      

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00095856 0.00154761 0.00088945 0.00138632 0.00085951 0.00157446]
  [0.00154761 0.00303344 0.00220394 0.00280331 0.00168299 0.00298152]
  [0.00088945 0.00220394 0.00225823 0.00208051 0.00124729 0.00227484]
  [0.00138632 0.00280331 0.00208051 0.00281398 0.00186994 0.00276417]
  [0.00085951 0.00168299 0.00124729 0.00186994 0.00163069 0.00179133]
  [0.00157446 0.00298152 0.00227484 0.00276417 0.00179133 0.00313568]]

 [[0.00320639 0.00237893 0.00145608 0.00237455 0.00159466 0.00261383]
  [0.00237893 0.00308278 0.00206985 0.00223155 0.00191525 0.00272854]
  [0.00145608 0.00206985 0.00197196 0.0015063  0.00111322 0.00169084]
  [0.00237455 0.00223155 0.0015063  0.00219452 0.00126598 0.00215924]
  [0.00159466 0.00191525 0.00111322 0.00126598 0.00152769 0.00196634]
  [0.00261383 0.00272854 0.00169084 0.00215924 0.00196634 0.00286515]]

 [[0.00126149 0.00173121 0.00124995 0.00128876 0.00186877 0.00071843]
  [0.00173121 0.00321042 0.00236346 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.287949                                                          
INFO: Iteration : 2, log likelihood : -0.291694                                                          
INFO: Iteration : 3, log likelihood : -0.406328                                                          
INFO: Iteration : 4, log likelihood : -2.961746                                                          
INFO: Iteration : 5, log likelihood : -6.190964                                                          
INFO: Iteration : 6, log likelihood : -9.212381                                               

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[2.49252564e-01 2.85585335e-06 2.50747436e-01 2.49997144e-01
  2.50000000e-01]]
[[2.50000000e-01 2.85585335e-06 2.50000000e-01 2.49997144e-01
  2.50000000e-01]]


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.287949                                                          
INFO: Iteration : 2, log likelihood : -0.291694                                                          
INFO: Iteration : 3, log likelihood : -0.406328                                                          
INFO: Iteration : 4, log likelihood : -2.961746                                                          
INFO: Iteration : 5, log likelihood : -6.190964     

In [36]:
import os
import newkernelo as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -31.777198                                                         
INFO: Iteration : 2, log likelihood : -33.585616                                                         
INFO: Iteration : 3, log likelihood : -170.120737                                                        
INFO: Iteration : 

In [37]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
