In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>
(50, 4, 4)
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00767434 0.00797319 0.00789052 ... 0.0075954  0.00815691 0.00783704]
  [0.00809359 0.00811229 0.00800514 ... 0.0079676  0.00783821 0.00769275]
  [0.0080464  0.00755432 0.00816927 ... 0.00781601 0.00752356 0.00762734]
  ...
  [0.00810578 0.00803066 0.00784803 ... 0.00796791 0.0078811  0.00766725]
  [0.00762579 0.00754225 0.00764154 ... 0.00804294 0.0076434  0.00777461]
  [0.00767828 0.00765309 0.00799249 ... 0.00809593 0.00809195 0.00802016]]

 [[0.00775738 0.00817025 0.00781144 ... 0.00753729 0.00809238 0.00772069]
  [0.00818116 0.00831279 0.00792491 ... 0.00790665 0.00777621 0.00757854]
  [0.00813346 0.00774103 0.00808739 ... 0.00775622 0.00746404 0.0075141 ]
  ...
  [0.00819348 0.00822914 0.00776938 ... 0.00790695 0.0078187

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.72256288 0.4266059  0.71004955 0.60414795 0.01452369 0.42334854]
 [0.08949959 0.54844338 0.86419774 0.65667172 0.97272074 0.20677657]
 [0.09436114 0.36108141 0.23688834 0.02426344 0.93092237 0.38065004]
 [0.50312213 0.83687368 0.76088762 0.85028385 0.15277628 0.67132572]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[10.22863719 10.22863719 10.22863719 10.22863719 10.22863719 10.22863719
  10.22863719 10.22863719 10.22863719]
 [12.5190131  12.5190131  12.5190131  12.5190131  12.5190131  12.5190131
  12.5190131  12.5190131  12.5190131 ]
 [13.7160697  13.7160697  13.7160697  13.7160697  13.7160697  13.7160697
  13.7160697  13.7160697  13.7160697 ]
 [12.40610088 12.40610088 12.40610088 12.40610088 12.40610088 12.40610088
  12.40610088 12.40610088 12.40610088]
 [12.21282925 12.21282925 12.21282925 12.21282925 12.21282925 12.21282925
  12.21282925 12.21282925 12.21282925]
 [11.04630261 11.04630261 11.04630261 11.04630261 11.04630261 11.04630261
  11.04630261 11.04630261 11.04630261]]
[[[1.09855055e+00 1.75745588e-25 1.75745588e-25 1.75745588e-25
   1.75745588e-25 1.75745588e-25 1.75745588e-25 1.75745588e-25
   1.75745588e-25]
  [1.75745588e-25 1.01456201e+00 1.75745588e-25 1.75745588e-25
   1.75745588e-25 1.75745588e-25 1.75745588e-25 1.75745588e-25
   1.75745588e-25]
  [1.75745588e-25 1.75745588e-25 

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.009635686874389648


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.042536258697509766


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.18570946 0.1712522  0.26364181 0.16120055]
 [0.18226404 0.1677892  0.26025867 0.15772958]
 [0.16114159 0.14660524 0.23960103 0.13648542]
 [0.18444229 0.16998596 0.26241079 0.15992957]
 [0.16335944 0.14883058 0.24177194 0.13871683]
 [0.1675059  0.15298695 0.24582327 0.14288554]
 [0.16823525 0.15372168 0.2465424  0.14362156]
 [0.17410559 0.15960872 0.25228284 0.14952542]
 [0.17995038 0.16547876 0.25801378 0.15541011]
 [0.18002028 0.16554546 0.25807604 0.15547784]
 [0.18504585 0.17059759 0.26301238 0.16054137]
 [0.17619395 0.16171229 0.25434161 0.15163271]
 [0.18572968 0.17127839 0.26367216 0.16122535]
 [0.16116445 0.14662463 0.23961705 0.13650574]
 [0.1750442  0.16055871 0.25321631 0.15047598]
 [0.17632334 0.16183893 0.25446255 0.15176048]
 [0.16641682 0.15189921 0.24476623 0.14179359]
 [0.17139966 0.15689204 0.24963132 0.14680173]
 [0.17540952 0.16092704 0.25357707 0.15084487]
 [0.17065729 0.15615078 0.24891115 0.14605755]
 [0.18223492 0.16777282 0.26025318 0.15770998]
 [0.161

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization


Generating dataset
Initializing GLLIM model


INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.681546, Best log likelihood : 25.681546
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.835868


Training model


INFO:root:Iteration : 2, log likelihood : 25.984621
INFO:root:Iteration : 3, log likelihood : 26.095258
INFO:root:Iteration : 4, log likelihood : 26.214115
INFO:root:Iteration : 5, log likelihood : 26.277127
INFO:root:Iteration : 6, log likelihood : 26.315584
INFO:root:Iteration : 7, log likelihood : 26.362580
INFO:root:Iteration : 8, log likelihood : 26.410716
INFO:root:Iteration : 9, log likelihood : 26.458788
INFO:root:Iteration : 10, log likelihood : 26.483471
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01482072 0.0100375  0.01700127 0.02099184 0.01598149 0.00799937
 0.00998556 0.007984   0.01793418 0.01300466 0.01895724 0.01292081
 0.03104028 0.03011726 0.02297622 0.0243902  0.05275097 0.0229692
 0.01995688 0.01911128 0.0100333  0.00996022 0.01706732 0.02222096
 0.01246875 0.02237354 0.01899422 0.0136376  0.02772536 0.01599711
 0.01193687 0.02965402 0.04119121 0.01092375 0.03050771 0.01241778
 0.02401281 0.03326807 0.01945226 0.0100056  0.01792704 0.01211928
 0.023401   0.02450649 0.01453936 0.01500267 0.02647652 0.02804905
 0.01997567 0.03322353]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00143398 0.00148953 0.00137193 0.001162   0.00148785 0.00201488]
  [0.00148953 0.00185344 0.00112144 0.00143339 0.0015297  0.00208961]
  [0.00137193 0.00112144 0.0019467  0.00089321 0.00137923 0.00193587]
  [0.001162   0.00143339 0.00089321 0.00130188 0.00099215 0.00155248]
  [0.00148785 0.0015297  0.00137923 0.00099215 0.00176807 0.00220618]
  [0.00201488 0.00208961 0.00193587 0.00155248 0.00220618 0.00332346]]

 [[0.00274879 0.00250063 0.00286231 0.00151146 0.00265215 0.00217938]
  [0.00250063 0.00298429 0.00252464 0.00145443 0.00257016 0.00242733]
  [0.00286231 0.00252464 0.00357881 0.00170954 0.00307157 0.0022605 ]
  [0.00151146 0.00145443 0.00170954 0.00123913 0.00184872 0.00115282]
  [0.00265215 0.00257016 0.00307157 0.00184872 0.00337548 0.00219294]
  [0.00217938 0.00242733 0.0022605  0.00115282 0.00219294 0.00209339]]

 [[0.0027205  0.00199159 0.0011336  0.00131052 0.00245846 0.00145876]
  [0.00199159 0.00188623 0.00098402 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : 0.149472                                                           
INFO: Iteration : 2, log likelihood : 0.148973                                                           
INFO: Iteration : 3, log likelihood : 0.149110                                                           
INFO: Iteration : 4, log likelihood : 0.149194                                                           
INFO: Iteration : 5, log likelihood : 0.149194                                                           
INFO: Iteration : 6, log likelihood : 0.149194                                                

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 0.48022918 -0.007444    0.68271759  0.20566115 -0.19449784]
 [ 0.79484278  0.67673772  0.42707272  0.27670187 -0.48967226]
 [ 0.74116532  0.44889939  1.31212325  0.71949178  0.57835379]
 [-0.41928714  0.57557869  0.91919947  0.05162453  1.16261981]
 [ 1.00497474  0.44293938  0.76653819  0.41601773  0.17487021]
 [-0.02941265 -0.21158981  0.93827617  0.86535356  0.36285742]
 [ 0.23353113  0.22793313  0.52658529  0.43708913  0.30240603]
 [ 0.10921184  0.17568113  0.65967817  0.92374155  1.24231327]
 [ 0.85832708  0.14763611  1.00164434  0.40541263  0.62051705]
 [ 0.30903538  1.17475416  0.21192228  0.69204782 -0.18614826]
 [ 0.91791561 -0.37041534 -0.19609227  0.64382989  0.70978627]
 [ 0.16583893  0.31418968  1.37246573  0.48301529  0.28748358]
 [ 0.78947691  1.60618713  0.43979625  0.75214107  0.82911718]
 [-0.00763258  0.14835651 -0.89865107  0.15343478  0.98243919]
 [ 0.71274152  1.57314971  0.46307851  1.05019343  0.33010627]
 [ 0.5449838   0.66551533  0.83907112  0.61081802  0.43

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : 0.149472                                                           
INFO: Iteration : 2, log likelihood : 0.148973                                                           
INFO: Iteration : 3, log likelihood : 0.149110                                                           
INFO: Iteration : 4, log likelihood : 0.149194                                                           
INFO: Iteration : 5, log likelihood : 0.149194      

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00081457 0.00077993 0.00096621 0.0003566  0.00096334 0.00113177]
  [0.00077993 0.00152009 0.00161064 0.00080149 0.00080919 0.00131133]
  [0.00096621 0.00161064 0.00281872 0.00100886 0.00148723 0.00250412]
  [0.0003566  0.00080149 0.00100886 0.00110478 0.00076326 0.0011868 ]
  [0.00096334 0.00080919 0.00148723 0.00076326 0.00185006 0.00182818]
  [0.00113177 0.00131133 0.00250412 0.0011868  0.00182818 0.00276755]]

 [[0.00210683 0.00151387 0.00114447 0.00209272 0.00197939 0.00158214]
  [0.00151387 0.00171899 0.00137543 0.00214673 0.00155501 0.00120286]
  [0.00114447 0.00137543 0.00152523 0.00203034 0.00168194 0.00099035]
  [0.00209272 0.00214673 0.00203034 0.00345244 0.0027     0.00139685]
  [0.00197939 0.00155501 0.00168194 0.0027     0.00308347 0.00138555]
  [0.00158214 0.00120286 0.00099035 0.00139685 0.00138555 0.00152461]]

 [[0.00130325 0.00071602 0.00153849 0.0005893  0.00106169 0.00149132]
  [0.00071602 0.00092325 0.00112485 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.292624                                                          
INFO: Iteration : 2, log likelihood : -0.283766                                                          
INFO: Iteration : 3, log likelihood : -0.353679                                                          
INFO: Iteration : 4, log likelihood : -4.420321                                                          
INFO: Iteration : 5, log likelihood : -11.740567                                                         
INFO: Iteration : 6, log likelihood : -18.800649                                              

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[2.50000000e-01 3.85842774e-04 5.00000000e-01 3.38923319e-06
  2.49610768e-01]]
[[2.50000000e-01 3.85842774e-04 5.00000000e-01 3.38923319e-06
  2.49610768e-01]]


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.292624                                                          
INFO: Iteration : 2, log likelihood : -0.283766                                                          
INFO: Iteration : 3, log likelihood : -0.353679                                                          
INFO: Iteration : 4, log likelihood : -4.420321                                                          
INFO: Iteration : 5, log likelihood : -11.740567    

In [36]:
import os
import newkernelo as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -31.799444                                                         
INFO: Iteration : 2, log likelihood : -32.399914                                                         
INFO: Iteration : 3, log likelihood : -59.575712                                                         
INFO: Iteration : 

In [37]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
