In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 5

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='full')
print(gllim.__doc__)
print(lib.GLLiM.__doc__)
# print(lib.FunctionalModel.__doc__)
# print(lib.ExternalPythonModel.__doc__)
# print(lib.ExternalPythonModel.__init__.__doc__)
help(lib.GLLiM)

NoneGLLiM Parameters initialized

None
Help on class GLLiM in module newkernelo:

class GLLiM(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      GLLiM
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(self: newkernelo.GLLiM, L: int, D: int, K: int, gamma_type: str, sigma_type: str) -> None
 |  
 |  directDensities(...)
 |      directDensities(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64], arg1: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |      
 |      2. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |  
 |  getDimensions(...)
 |      getDimensions(self: newkernelo.GLLiM) -> str
 |  
 |  getInverse(...)
 |      getInverse(self: newkernelo.GLLiM) -> newkernelo.GLLiMParameters
 |  
 |  getParamA(...)
 |      

In [3]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
print(theta.L)

[[0. 0. 0. 0. 0.]]
(9, 4, 5)
4


In [4]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=5)


In [5]:
gllim.getInverse().C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((L, L, K)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((D, D, K)) * 0.3

gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(Sigma)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.

In [7]:
new_theta = lib.GLLiMParameters(L,D,K)

Gamma = np.ones((L,L,K)) + np.random.rand(L,L,K) * 0.1
Sigma = np.ones((D,D,K)) + np.random.rand(D,D,K) * 0.1
for k in range(K):
    Gamma[:,:,k] += np.eye(L) * 0.1
    Gamma[:,:,k] = np.dot(Gamma[:,:,k], Gamma[:,:,k].T) * 0.001
    Sigma[:,:,k] += np.eye(D) * 0.1
    Sigma[:,:,k] = np.dot(Sigma[:,:,k], Sigma[:,:,k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 2
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma

gllim.setParams(new_theta)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[[0.00474974 0.00445467 0.00446992 0.00452137 0.00438038]
  [0.00452822 0.00449975 0.00451938 0.00454831 0.00452228]
  [0.00473469 0.00454948 0.00457171 0.00467766 0.00442951]
  [0.00474678 0.00455324

In [8]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[-3.56248274e-01  1.39756369e-01  9.11342324e-02 -4.39009823e-01
   -9.01946205e+00]
  [ 3.26852720e-01  3.84052704e-01  5.27737226e-01 -3.93878599e-01
   -5.70858869e+00]
  [-5.54447843e-03  2.32170413e-01 -1.18940552e+00 -1.39483719e+00
    3.77281915e+00]
  [-8.16498352e-01 -1.12299667e+00 -1.11560894e+00  1.41571986e+00
   -2.49023801e+00]
  [ 2.59254798e-02  1.95052624e-01 -7.47153676e-01  9.03569627e-01
    6.99077969e+00]
  [ 6.90704010e-01 -2.72652650e-01  1.01541633e+00  1.75660041e+00
   -9.22915487e+00]
  [-5.22538434e-01 -6.27699485e-01  1.25947381e+00 -1.07041678e+00
    1.16467635e+01]
  [ 7.31789232e-01  6.86901333e-01 -1.63655486e+00  1.98041298e-01
    4.46517994e+00]
  [ 4.86904599e-02  5.05101607e-01  1.91660067e+00 -8.55615823e-01
   -3.05683730e-01]]

 [[-3.41451785e-01  1.41667109e-01  9.24673760e-02 -4.43911131e-01
   -9.34528885e+00]
  [ 3.13277151e-01  3.89303448e-01  5.35457152e-01 -3.98276041e-01
   -5.91481066e+00]
  [-5.31419292e-0

In [9]:
x = np.random.rand(L, 2)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.66028714 0.49316277]
 [0.46762954 0.1528085 ]
 [0.6534406  0.12360591]
 [0.82531485 0.80623636]]


In [10]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[11.21334424 11.21334424 11.21334424 11.21334424 11.21334424 11.21334424
  11.21334424 11.21334424 11.21334424]
 [ 9.15162709  9.15162709  9.15162709  9.15162709  9.15162709  9.15162709
   9.15162709  9.15162709  9.15162709]]
[[[0.01016953 0.01019141 0.01026802 0.01009333 0.01015129 0.00998442
   0.01015585 0.01012288 0.01003357]
  [0.01019141 0.01023564 0.010304   0.01012456 0.01018058 0.01002455
   0.01019396 0.01015786 0.01006951]
  [0.01026802 0.010304   0.01040415 0.01020902 0.01025841 0.01011368
   0.01028272 0.0102418  0.01014936]
  [0.01009333 0.01012456 0.01020902 0.0100567  0.01007313 0.00992892
   0.01011331 0.01006086 0.00998064]
  [0.01015129 0.01018058 0.01025841 0.01007313 0.01015141 0.00997673
   0.01014708 0.01011324 0.01002259]
  [0.00998442 0.01002455 0.01011368 0.00992892 0.00997673 0.00985691
   0.01000899 0.00997025 0.00988608]
  [0.01015585 0.01019396 0.01028272 0.01011331 0.01014708 0.01000899
   0.01019721 0.01014541 0.01004832]
  [0.01012288 0.01015786 0.0102

In [11]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.000453948974609375


In [12]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [13]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.003023386001586914


In [14]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[-0.33484448 -0.49144013 -0.38668104 -0.4867524 ]
 [-0.53038024 -0.34221449 -0.52723877 -0.54471035]
 [-0.33864673 -0.38708538 -0.5013125  -0.46152358]
 [-0.52428871 -0.57479996 -0.69391462 -0.65242321]
 [-0.63937909 -0.44668616 -0.63616205 -0.65405399]
 [-0.49998465 -0.66254596 -0.55379597 -0.65767965]
 [-0.25182488 -0.30995555 -0.35501    -0.35936822]
 [-0.38038647 -0.42929113 -0.54461716 -0.50444545]
 [-0.51246535 -0.57415948 -0.62197581 -0.62660119]
 [-0.4231786  -0.47256101 -0.58901366 -0.54844952]
 [-0.25708466 -0.41087125 -0.30799135 -0.40626761]
 [-0.5432537  -0.59397668 -0.71359065 -0.67192532]
 [-0.30738574 -0.36627604 -0.41191924 -0.41633441]
 [-0.53323575 -0.34495139 -0.5300923  -0.54757489]
 [-0.46023641 -0.51003255 -0.62746086 -0.58655686]
 [-0.40940466 -0.45863329 -0.57472331 -0.53428548]
 [-0.49467023 -0.54485081 -0.66318568 -0.6219659 ]
 [-0.55215083 -0.60297315 -0.72282136 -0.68107443]
 [-0.4115128  -0.46076497 -0.57691049 -0.53645333]
 [-0.31420797 -0.47005812

# GLLiM TRAIN

In [15]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 5, "Full", "Full", initConfig, learningConfig)


In [16]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(500)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 45.302044, Best log likelihood : 45.302044
INFO:root:Finish Multi initialization


Generating dataset
Initializing GLLIM model
Training model


### Get theta_0 from oldker

In [17]:
theta_0 = lib.GLLiMParameters(L,D,K)

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(5,)
(5, 9, 4)
(4, 5)
(5, 4, 4)
(9, 5)
(5, 9, 9)
[0.19921497 0.22916334 0.15993857 0.20980127 0.20188186]
(9, 4, 5)
(4, 5)
(4, 4, 5)
(9, 5)
(9, 9, 5)
0.9999999999999996


In [18]:
theta_0 = theta
print(theta_0.Pi)
print(theta_0.C)

jgmm = lib.JGMM()
theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
print(theta_0.Pi)
print(theta_jgmm.Pi)
print(theta_0.C)
print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

[[0.2 0.2 0.2 0.2 0.2]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
K=5
n_dims=13
n_gaus=5
135
13135
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 896430
gmm_full::learn(): k-means: iteration:    2   delta: 1.62711
gmm_full::learn(): k-means: iteration:    3   delta: 0.439549
gmm_full::learn(): k-means: iteration:    4   delta: 0.063693
gmm_full::learn(): k-means: iteration:    5   delta: 0.0292287
gmm_full::learn(): k-means: iteration:    6   delta: 0.0105795
gmm_full::learn(): k-means: iteration:    7   delta: 0.0116793
gmm_full::learn(): k-means: iteration:    8   delta: 0.00574088
gmm_full::learn(): k-means: iteration:    9   delta: 0.00285171
gmm_full::learn(): k-means: iteration:   10   delta: 0.000419998
gmm_full::learn(): k-means: iteration:   11   delta: 0
gmm_full::learn(): EM: n_threads: 8
gmm_full::learn(): EM: iteration:    1   avg_log_p: -2.2

   3   avg_log_p: -6.94441
gmm_full::learn(): EM: iteration:    4   avg_log_p: -7.11807
gmm_full::learn(): EM: iteration:    5   avg_log_p: -7.29145
gmm_full::learn(): EM: iteration:    6   avg_log_p: -7.46476
gmm_full::learn(): EM: iteration:    7   avg_log_p: -7.63805
gmm_full::learn(): EM: iteration:    8   avg_log_p: -7.81134
gmm_full::learn(): EM: iteration:    9   avg_log_p: -7.98462
gmm_full::learn(): EM: iteration:   10   avg_log_p: -8.15791
[[0.2 0.2 0.2 0.2 0.2]]
[[2.49999955e-01 2.49999955e-01 1.78813945e-07 2.49999955e-01
  2.49999955e-01]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[0.00000000e+000 2.32636052e-248 7.94787177e-001 2.87125173e-229
  5.03901954e-228]
 [0.00000000e+000 1.42313884e-247 3.66985453e-001 1.93056723e-229
  8.21705398e-229]
 [7.14940602e-220 1.10888778e-247 4.91087464e-001 2.82997824e-229
  5.30034866e-228]
 [7.55478219e-220 1.42078459e-247 3.07718211e-001 3.18228572e-229
  6.89442102e-228]]


In [19]:
# print(theta.Pi)
gllim.setParams(theta)


print(gllim.getParamPi())
print(gllim.getParamC())
gllim.train(x_gen, y_gen, 15, 100, 1e-12)
time.sleep(1)
print(gllim.getParamPi()) 
print(gllim.getParamC())

# TODO le gllim.getParamPi() doit changer !


[[0.2 0.2 0.2 0.2 0.2]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
Joint GMM training
K=5
n_dims=13
n_gaus=5
135
13135
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 895680
gmm_full::learn(): k-means: iteration:    2   delta: 2.05933
gmm_full::learn(): k-means: iteration:    3   delta: 0.528429
gmm_full::learn(): k-means: iteration:    4   delta: 0.136182
gmm_full::learn(): k-means: iteration:    5   delta: 0.0242227
gmm_full::learn(): k-means: iteration:    6   delta: 0.00467024
gmm_full::learn(): k-means: iteration:    7   delta: 0.00537634
gmm_full::learn(): k-means: iteration:    8   delta: 0.00144777
gmm_full::learn(): k-means: iteration:    9   delta: 0.00069022
gmm_full::learn(): k-means: iteration:   10   delta: 0.000173984
gmm_full::learn(): k-means: iteration:   11   delta: 0.0003406
gmm_full::learn(): k-means: iteration:   12   delta: 0.00284354

[[0.2 0.2 0.2 0.2 0.2]]
[[0.56323466 0.24973366 0.51131604 0.78591845 0.46333104]
 [0.60416069 0.25122514 0.52331669 0.2964939  0.80125996]
 [0.4755053  0.5142223  0.50487274 0.49075838 0.51556756]
 [0.84283615 0.4729581  0.4873953  0.34089177 0.29788986]]


In [20]:
print(gllim_parameters.Pi)
print(theta_jgmm.Pi)
print(gllim.getParamPi())

[0.19921497 0.22916334 0.15993857 0.20980127 0.20188186]
[[2.49999955e-01 2.49999955e-01 1.78813945e-07 2.49999955e-01
  2.49999955e-01]]
[[0.2 0.2 0.2 0.2 0.2]]


## GLLM training : EM estimator : full/diag

In [22]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')

diag_gllim.setParams(theta_0)

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [27]:
print(diag_gllim.getParamB())
diag_gllim.train(x_gen, y_gen, 15, 100, 1e-12)
print(diag_gllim.getParamB())

[[96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]
 [96. 96. 96. 96. 96.]]
[[192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]
 [192. 192. 192. 192. 192.]]
GLLiM training
EmEstimator train
