In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>
(50, 4, 4)
GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00839903 0.00792568 0.00807837 ... 0.00812165 0.00783881 0.00748271]
  [0.00797794 0.00799945 0.00821516 ... 0.00774766 0.00809855 0.00763696]
  [0.00780664 0.00752229 0.00762466 ... 0.00831493 0.00767862 0.0081483 ]
  ...
  [0.00789443 0.00782393 0.0075359  ... 0.00834265 0.00762885 0.00811595]
  [0.00835464 0.00799015 0.00800022 ... 0.00781668 0.00751979 0.00808637]
  [0.00800317 0.00811151 0.00786013 ... 0.00806922 0.0078958  0.0080999 ]]

 [[0.00840606 0.00804876 0.00804847 ... 0.0077039  0.00791549 0.00731156]
  [0.00798462 0.00812368 0.00818476 ... 0.00734915 0.00817777 0.00746229]
  [0.00781317 0.00763911 0.00759644 ... 0.00788724 0.00775373 0.00796193]
  ...
  [0.00790104 0.00794544 0.00750801 ... 0.00791353 0.0077034

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.58729521 0.83274511 0.93037084 0.28160834 0.91200817 0.64459638]
 [0.15406444 0.72662543 0.73484475 0.93683107 0.89822926 0.20494884]
 [0.11047603 0.02223056 0.56889071 0.83937559 0.30548022 0.99621775]
 [0.19591577 0.42002716 0.24931374 0.02646606 0.10941264 0.2009137 ]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[ 9.14325437  9.14325437  9.14325437  9.14325437  9.14325437  9.14325437
   9.14325437  9.14325437  9.14325437]
 [12.0048848  12.0048848  12.0048848  12.0048848  12.0048848  12.0048848
  12.0048848  12.0048848  12.0048848 ]
 [13.45026012 13.45026012 13.45026012 13.45026012 13.45026012 13.45026012
  13.45026012 13.45026012 13.45026012]
 [12.25284316 12.25284316 12.25284316 12.25284316 12.25284316 12.25284316
  12.25284316 12.25284316 12.25284316]
 [12.67539089 12.67539089 12.67539089 12.67539089 12.67539089 12.67539089
  12.67539089 12.67539089 12.67539089]
 [12.14003001 12.14003001 12.14003001 12.14003001 12.14003001 12.14003001
  12.14003001 12.14003001 12.14003001]]
[[[1.02746096e+00 3.03238132e-27 3.03238132e-27 3.03238132e-27
   3.03238132e-27 3.03238132e-27 3.03238132e-27 3.03238132e-27
   3.03238132e-27]
  [3.03238132e-27 1.01361531e+00 3.03238132e-27 3.03238132e-27
   3.03238132e-27 3.03238132e-27 3.03238132e-27 3.03238132e-27
   3.03238132e-27]
  [3.03238132e-27 3.03238132e-27

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.008033275604248047


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.029398202896118164


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.15112206 0.15595145 0.2725841  0.20875675]
 [0.1514068  0.16138886 0.2745869  0.21206762]
 [0.13893614 0.14619347 0.26153459 0.19815577]
 [0.15159604 0.15887632 0.27389622 0.21067438]
 [0.15991219 0.16839123 0.28235168 0.21957609]
 [0.14670135 0.15371465 0.26903636 0.20568426]
 [0.13575813 0.14558954 0.25940374 0.19656143]
 [0.14158132 0.15254792 0.26558191 0.20301426]
 [0.1601797  0.16386667 0.2809029  0.21699228]
 [0.14533068 0.15293242 0.2679273  0.20468542]
 [0.1430732  0.14837808 0.26481594 0.20106481]
 [0.15150245 0.15945654 0.2739517  0.2109554 ]
 [0.14217533 0.14853971 0.26443348 0.20084098]
 [0.15147303 0.15704546 0.27311792 0.20952375]
 [0.14597965 0.1573822  0.26985884 0.20756868]
 [0.15636801 0.16095626 0.27755089 0.21377611]
 [0.14181721 0.14735304 0.26379291 0.19999611]
 [0.15737893 0.16327705 0.27905589 0.21556792]
 [0.15817236 0.16739143 0.28090076 0.2182924 ]
 [0.14183497 0.14852224 0.26412097 0.20066911]
 [0.13948808 0.1490943  0.26291891 0.20009917]
 [0.139

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means


Generating dataset
Initializing GLLIM model


INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.686131, Best log likelihood : 25.686131
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.865265


Training model


INFO:root:Iteration : 2, log likelihood : 26.036052
INFO:root:Iteration : 3, log likelihood : 26.145424
INFO:root:Iteration : 4, log likelihood : 26.242797
INFO:root:Iteration : 5, log likelihood : 26.317831
INFO:root:Iteration : 6, log likelihood : 26.376389
INFO:root:Iteration : 7, log likelihood : 26.425289
INFO:root:Iteration : 8, log likelihood : 26.467357
INFO:root:Iteration : 9, log likelihood : 26.483786
INFO:root:Iteration : 10, log likelihood : 26.503304
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01792812 0.00999484 0.01903612 0.01801102 0.01690249 0.00798751
 0.01500626 0.00799194 0.01693377 0.01300314 0.0189042  0.01294576
 0.03207152 0.02643702 0.02291484 0.02496531 0.04935228 0.02294004
 0.01995539 0.01711886 0.01007503 0.0099155  0.01706    0.02000229
 0.0120667  0.02235329 0.01996603 0.01432498 0.02877093 0.01693479
 0.01094734 0.02926848 0.04071459 0.01364809 0.027076   0.01099798
 0.0240182  0.03190136 0.01775899 0.01063794 0.01753568 0.01014103
 0.02293897 0.02902528 0.01499639 0.01600024 0.02952538 0.02805027
 0.0199735  0.0329743 ]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/diag

In [24]:
L, D, K, N = 10, 100, 5, 100
new_theta = lib.GLLiMParameters(L,D,K, "iso", "diag")

Gamma = np.random.rand(K)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
# for k in range(K):
#     Gamma[k,:,:] += np.eye(L) * 0.1
#     Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.ones((D, L, K)) * 0.3
new_theta.C = np.ones((L, K)) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.ones((D, K)) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [25]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='iso', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=10, D=100, K=5)
GLLiM constraints are :
	gamma_type = 'iso',
	sigma_type = 'diag'.


In [26]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[0.6436546 ]
 [0.93429877]
 [0.83887086]
 [0.83066971]
 [0.68124057]]
[[0.6436546 ]
 [0.93429877]
 [0.83887086]
 [0.83066971]
 [0.68124057]]


In [27]:
print(diag_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 3, 10, 1e-12)
print(diag_gllim.getParamB())
print(diag_gllim.getParamSigma())

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0