In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>GLLiM Parameters initialized

(50, 4, 4)
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00758718 0.00750385 0.00761084 ... 0.00774204 0.00778212 0.0075195 ]
  [0.00784011 0.00799826 0.00784202 ... 0.00785299 0.0077251  0.00795365]
  [0.00828579 0.00756566 0.00807231 ... 0.00794102 0.00751032 0.00761032]
  ...
  [0.00786896 0.00791333 0.0079759  ... 0.00792589 0.00790454 0.00783864]
  [0.0078412  0.00771284 0.00811663 ... 0.00785006 0.00750597 0.00808738]
  [0.0076976  0.00770308 0.00769465 ... 0.0077887  0.00778309 0.00823308]]

 [[0.00744491 0.00783878 0.00759522 ... 0.00761012 0.00785215 0.00747028]
  [0.0076931  0.00835525 0.00782592 ... 0.00771917 0.00779462 0.00790159]
  [0.00813041 0.00790335 0.00805574 ... 0.00780571 0.00757791 0.00756051]
  ...
  [0.00772141 0.00826653 0.00795953 ... 0.00779083 0.0079756

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.6043491  0.19137506 0.28061095 0.55618265 0.0507064  0.17597186]
 [0.10892178 0.29215175 0.29573396 0.27764447 0.90080152 0.00593909]
 [0.51299102 0.92647137 0.59861871 0.22344224 0.36492024 0.17778984]
 [0.12884354 0.64758606 0.9178576  0.03988556 0.4005927  0.63978553]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[10.06531635 10.06531635 10.06531635 10.06531635 10.06531635 10.06531635
  10.06531635 10.06531635 10.06531635]
 [12.17275271 12.17275271 12.17275271 12.17275271 12.17275271 12.17275271
  12.17275271 12.17275271 12.17275271]
 [12.27846367 12.27846367 12.27846367 12.27846367 12.27846367 12.27846367
  12.27846367 12.27846367 12.27846367]
 [ 9.29146477  9.29146477  9.29146477  9.29146477  9.29146477  9.29146477
   9.29146477  9.29146477  9.29146477]
 [11.15106256 11.15106256 11.15106256 11.15106256 11.15106256 11.15106256
  11.15106256 11.15106256 11.15106256]
 [ 8.99845897  8.99845897  8.99845897  8.99845897  8.99845897  8.99845897
   8.99845897  8.99845897  8.99845897]]
[[[1.09034981e+00 1.87086252e-26 1.87086252e-26 1.87086252e-26
   1.87086252e-26 1.87086252e-26 1.87086252e-26 1.87086252e-26
   1.87086252e-26]
  [1.87086252e-26 1.02360637e+00 1.87086252e-26 1.87086252e-26
   1.87086252e-26 1.87086252e-26 1.87086252e-26 1.87086252e-26
   1.87086252e-26]
  [1.87086252e-26 1.87086252e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.00543212890625


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.03795433044433594


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.12603359 0.31055561 0.15001698 0.16230304]
 [0.13397682 0.31700692 0.15760258 0.16942484]
 [0.12193245 0.30575231 0.14569263 0.15763818]
 [0.12864049 0.31261709 0.15249106 0.16460291]
 [0.11588484 0.30035233 0.13978208 0.15188837]
 [0.13129959 0.31505533 0.15510761 0.16717391]
 [0.12766449 0.31196667 0.15159842 0.16382328]
 [0.12435523 0.30792973 0.1480644  0.15995111]
 [0.12733409 0.31130438 0.15117376 0.16326277]
 [0.12648481 0.31055818 0.15034709 0.16246345]
 [0.12364274 0.30753979 0.1474363  0.15943885]
 [0.1159123  0.30084288 0.139938   0.15222714]
 [0.1339345  0.31723434 0.15763467 0.16956255]
 [0.13399163 0.31483466 0.15701168 0.16797276]
 [0.14124253 0.32343347 0.16468668 0.17629183]
 [0.12624333 0.31001002 0.15001897 0.16201077]
 [0.1238183  0.30777206 0.14762877 0.15965648]
 [0.12579566 0.30937976 0.14951758 0.16143052]
 [0.12102135 0.30493555 0.14480128 0.15676977]
 [0.13564157 0.31817421 0.1591412  0.17079345]
 [0.13216396 0.31586553 0.15596302 0.16802147]
 [0.114

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


Generating dataset

INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model



Initializing GLLIM model


INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.681769, Best log likelihood : 25.681769
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.869668
INFO:root:Iteration : 2, log likelihood : 26.022530
INFO:root:Iteration : 3, log likelihood : 26.139552
INFO:root:Iteration : 4, log likelihood : 26.240616


Training model


INFO:root:Iteration : 5, log likelihood : 26.316912
INFO:root:Iteration : 6, log likelihood : 26.373214
INFO:root:Iteration : 7, log likelihood : 26.417165
INFO:root:Iteration : 8, log likelihood : 26.451327
INFO:root:Iteration : 9, log likelihood : 26.468156
INFO:root:Iteration : 10, log likelihood : 26.483021
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01495885 0.01000045 0.01908784 0.01801503 0.01695428 0.00799938
 0.01194644 0.00798446 0.01697066 0.01300314 0.01892481 0.01299312
 0.03211615 0.02950202 0.02352551 0.02494895 0.04817654 0.02293954
 0.01995766 0.01801595 0.01010014 0.00989742 0.0170647  0.02000271
 0.01262276 0.02235914 0.01996562 0.01467984 0.02872744 0.01693586
 0.01092956 0.02918769 0.03993826 0.01256338 0.02796551 0.01099724
 0.02401897 0.03291998 0.01985605 0.01085262 0.01700766 0.01215944
 0.02370111 0.02707622 0.01498728 0.01500387 0.02941564 0.02804834
 0.01997073 0.03302401]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(N,L)
Y_gen = np.random.rand(N,D)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00193222 0.00118392 0.00157186 0.00182432 0.0008761  0.00148578]
  [0.00118392 0.00164744 0.00114091 0.00109931 0.00058444 0.00100746]
  [0.00157186 0.00114091 0.00161583 0.00115247 0.0007194  0.0012698 ]
  [0.00182432 0.00109931 0.00115247 0.00234181 0.00123134 0.00137037]
  [0.0008761  0.00058444 0.0007194  0.00123134 0.00135401 0.00077416]
  [0.00148578 0.00100746 0.0012698  0.00137037 0.00077416 0.00148809]]

 [[0.0017893  0.00205668 0.00159762 0.0016101  0.00166078 0.0012988 ]
  [0.00205668 0.00252271 0.00197191 0.00192493 0.00185791 0.00126021]
  [0.00159762 0.00197191 0.00188143 0.00162313 0.00192983 0.00143677]
  [0.0016101  0.00192493 0.00162313 0.0018835  0.00154244 0.00138519]
  [0.00166078 0.00185791 0.00192983 0.00154244 0.00254668 0.0021034 ]
  [0.0012988  0.00126021 0.00143677 0.00138519 0.0021034  0.00246638]]

 [[0.00259367 0.00232642 0.00161801 0.00264132 0.00164072 0.00105861]
  [0.00232642 0.00265258 0.00166299 0.

In [27]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
Joint GMM training
K=5
n_dims=36
n_gaus=5
365
36365
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 86.6071
gmm_full::learn(): k-means: iteration:    2   delta: 0.00202646
gmm_full::learn(): k-means: iteratio

## GLLM training : EM estimator : full/diag

In [46]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [47]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [48]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00203755 0.00166023 0.0014533  0.00082191 0.00201748 0.00177414]
  [0.00166023 0.0022179  0.00141841 0.00157945 0.00239241 0.00172981]
  [0.0014533  0.00141841 0.00157372 0.00138635 0.00191169 0.0013564 ]
  [0.00082191 0.00157945 0.00138635 0.00209852 0.0019018  0.00106526]
  [0.00201748 0.00239241 0.00191169 0.0019018  0.00289079 0.00177259]
  [0.00177414 0.00172981 0.0013564  0.00106526 0.00177259 0.00225834]]

 [[0.00219306 0.00195197 0.00204357 0.00190356 0.00081643 0.00227967]
  [0.00195197 0.00233435 0.00179257 0.00117132 0.0007541  0.0021124 ]
  [0.00204357 0.00179257 0.00243413 0.00200544 0.00079482 0.00248718]
  [0.00190356 0.00117132 0.00200544 0.00249702 0.00091655 0.00207137]
  [0.00081643 0.0007541  0.00079482 0.00091655 0.00059509 0.00086542]
  [0.00227967 0.0021124  0.00248718 0.00207137 0.00086542 0.00273873]]

 [[0.00194904 0.00180544 0.00172995 0.0010715  0.00044233 0.00184579]
  [0.00180544 0.00208224 0.0015205  0.

In [49]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
[[0.        0.2658802 0.2341198 0.        0.5      ]]
GLLiM-EM training
Start GLLiM-EM Training
Iteration : 1, log likelihood : -3158.847351
Iteration : 2, log likelihood : -3380.895592
Iteration : 3, log likelihood : -3602.943834
Iteration : 4, log likelihood : -3824.992075
Iteration : 5, log likelihood : -4047.040317
Iteration : 6, log likelihood : -4269.088559
Iteration : 7, log likelihood : -4491.136800
Iteration : 8, log likelihood : -4713.185042
Iteration : 9, log likelihood : -4935.233284
Iteration : 10, log likelihood : -5157.281525
Iteration : 11, log likelihood : -5379.329767
Iteration : 12, log likelihood : -5601.378009
Iteration : 13, log likelihood : -5823.426250
Iteration : 14, log likelihood : -6045.474492
Iteration : 15, log likelihood : -6267.522734
Iteration : 16, log likelihood : -6489.570975
Iteration : 17, log likelihood : -6711.619217
Iteration : 18, log likelihood : -6933.667459
Iteration : 19, log likelihood : -7155.715700
Iteration : 20,