In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 5

gllim = lib.GLLiM(L,D,K)
print(gllim.__doc__)
print(lib.GLLiM.__doc__)
# print(lib.FunctionalModel.__doc__)
# print(lib.ExternalPythonModel.__doc__)
# print(lib.ExternalPythonModel.__init__.__doc__)
help(lib.GLLiM)

None
None
Help on class GLLiM in module newkernelo:

class GLLiM(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      GLLiM
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(self: newkernelo.GLLiM, L: int, D: int, K: int) -> None
 |  
 |  directDensities(...)
 |      directDensities(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64], arg1: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |      
 |      2. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |  
 |  getDimensions(...)
 |      getDimensions(self: newkernelo.GLLiM) -> str
 |  
 |  getInverse(...)
 |      getInverse(self: newkernelo.GLLiM) -> newkernelo.GLLiMParameters
 |  
 |  getParamA(...)
 |      getParamA(self: newkernelo.GLLiM) -> Numpy.ndarray[numpy.float6

In [3]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
print(theta.L)

[[0. 0. 0. 0. 0.]]
(9, 4, 5)
4


In [4]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=5)


In [5]:
gllim.getInverse().C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((L, L, K)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((D, D, K)) * 0.3

gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(Sigma)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.

In [7]:
new_theta = lib.GLLiMParameters(L,D,K)

Gamma = np.ones((L,L,K)) + np.random.rand(L,L,K) * 0.1
Sigma = np.ones((D,D,K)) + np.random.rand(D,D,K) * 0.1
for k in range(K):
    Gamma[:,:,k] += np.eye(L) * 0.1
    Gamma[:,:,k] = np.dot(Gamma[:,:,k], Gamma[:,:,k].T) * 0.001
    Sigma[:,:,k] += np.eye(D) * 0.1
    Sigma[:,:,k] = np.dot(Sigma[:,:,k], Sigma[:,:,k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 2
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma

gllim.setParams(new_theta)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[[0.00472398 0.00475146 0.00476957 0.0046181  0.00470929]
  [0.00471987 0.00451366 0.00458207 0.00465358 0.00469026]
  [0.00468284 0.00465234 0.00474945 0.00464158 0.00457418]
  [0.00464    0.00467914

In [8]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[ 2.34926842  1.5819375   0.38274601  0.28641341  2.58125421]
  [-0.31947797 -1.24844234  0.76574261 -0.86664079  0.12718529]
  [-0.09757409  0.12403633  0.22443484 -1.75638865 -1.13360731]
  [-1.74248104 -1.47152823 -0.53212658  0.85890075 -1.32623306]
  [-0.23282606  1.85661595 -1.15798318 -0.23370911  6.38295891]
  [ 0.21963782  0.84616104  0.69794843  0.95054178  1.00078941]
  [-1.18044622 -1.00887447  0.46421928  0.79163477 -3.90113435]
  [ 0.99014056  0.25082377 -0.69731289  0.19404389  0.28808366]
  [ 0.13706069 -0.8064812  -0.02404738 -0.10314043 -3.89538627]]

 [[ 2.34952989  1.50757077  0.36915146  0.28953617  2.57883284]
  [-0.31951353 -1.18975319  0.73854461 -0.87608976  0.12706599]
  [-0.09758495  0.11820539  0.21646326 -1.77553853 -1.13254392]
  [-1.74267498 -1.40235183 -0.51322626  0.86826533 -1.32498897]
  [-0.23285197  1.76933661 -1.11685339 -0.23625723  6.37697131]
  [ 0.21966227  0.80638309  0.67315837  0.96090553  0.99985061]
  [-1.1805776 

In [9]:
x = np.random.rand(L, 2)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.1120024  0.6421888 ]
 [0.4491765  0.98806938]
 [0.53899091 0.98708831]
 [0.87183913 0.38222885]]


In [10]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[ 9.94401788  9.94401788  9.94401788  9.94401788  9.94401788  9.94401788
   9.94401788  9.94401788  9.94401788]
 [11.99915067 11.99915067 11.99915067 11.99915067 11.99915067 11.99915067
  11.99915067 11.99915067 11.99915067]]
[[[0.00995012 0.00995564 0.0099882  0.01014329 0.01009373 0.01003327
   0.01005208 0.01024696 0.01012278]
  [0.00995564 0.01001717 0.01002885 0.01017358 0.01014698 0.01007118
   0.0100959  0.01028493 0.01015956]
  [0.0099882  0.01002885 0.01006444 0.01019519 0.01017061 0.01009859
   0.01011794 0.01031238 0.01019146]
  [0.01014329 0.01017358 0.01019519 0.01036362 0.01031539 0.01024707
   0.01026921 0.01047379 0.01033929]
  [0.01009373 0.01014698 0.01017061 0.01031539 0.01029273 0.01021674
   0.01024078 0.01043578 0.01030566]
  [0.01003327 0.01007118 0.01009859 0.01024707 0.01021674 0.01016265
   0.01016695 0.01037376 0.01023137]
  [0.01005208 0.0100959  0.01011794 0.01026921 0.01024078 0.01016695
   0.01019807 0.01038488 0.01025467]
  [0.01024696 0.01028493 0.0103

In [11]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.0006983280181884766


In [12]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [13]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.0030629634857177734


In [14]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[-0.70542763 -0.48422593 -0.62233992 -0.65384775]
 [-0.69637741 -0.74758194 -0.73860781 -0.68250228]
 [-0.59901527 -0.64915826 -0.64037017 -0.58542778]
 [-0.60731477 -0.65754825 -0.6487443  -0.59370277]
 [-0.42146663 -0.21361391 -0.34339307 -0.37299948]
 [-0.5183201  -0.3059143  -0.43853631 -0.46879125]
 [-0.67919957 -0.51300156 -0.6741488  -0.62191589]
 [-0.78068866 -0.61853185 -0.7101361  -0.72079451]
 [-0.45227499 -0.45277052 -0.420134   -0.37836382]
 [-0.08345078 -0.08390526 -0.05397233 -0.01566238]
 [-0.57234032 -0.35739504 -0.49160265 -0.52221932]
 [-1.0216298  -1.0169192  -0.89010544 -1.12085602]
 [-0.48984932 -0.27878194 -0.41056826 -0.44063257]
 [-0.7845153  -0.55959569 -0.70003108 -0.73206848]
 [-0.51598851 -0.56522627 -0.55659683 -0.50264632]
 [-0.82274625 -0.65144969 -0.81754054 -0.76370524]
 [-0.25726391 -0.25773774 -0.2265307  -0.18659008]
 [-0.48828419 -0.4840739  -0.37072899 -0.57697163]
 [-0.66263174 -0.44344187 -0.58029972 -0.61152098]
 [-0.71111772 -0.48964852

# GLLiM TRAIN

In [15]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 5, "Full", "Full", initConfig, learningConfig)


In [16]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(500)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 46.172271, Best log likelihood : 46.172271
INFO:root:Finish Multi initialization


Generating dataset
Initializing GLLIM model
Training model


### Get theta_0 from oldker

In [17]:
theta_0 = lib.GLLiMParameters(L,D,K)

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))

gllim.setParams(theta_0)

(5,)
(5, 9, 4)
(4, 5)
(5, 4, 4)
(9, 5)
(5, 9, 9)
[0.20203492 0.2270894  0.15980739 0.21153459 0.1995337 ]
(9, 4, 5)
(4, 5)
(4, 4, 5)
(9, 5)
(9, 9, 5)


In [18]:
theta_0 = theta
print(theta_0.Pi)
print(theta_0.C)

jgmm = lib.JGMM()
theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
print(theta_0.Pi)
print(theta_jgmm.Pi)
print(theta_0.C)
print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

[[0.2 0.2 0.2 0.2 0.2]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
K=5
n_dims=13
n_gaus=5
135
13135
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 896440
gmm_full::learn(): k-means: iteration:    2   delta: 1.62706
gmm_full::learn(): k-means: iteration:    3   delta: 0.439542
gmm_full::learn(): k-means: iteration:    4   delta: 0.063695
gmm_full::learn(): k-means: iteration:    5   delta: 0.0292299
gmm_full::learn(): k-means: iteration:    6   delta: 0.01058
gmm_full::learn(): k-means: iteration:    7   delta: 0.01168
gmm_full::learn(): k-means: iteration:    8   delta: 0.00574054
gmm_full::learn(): k-means: iteration:    9   delta: 0.00285144
gmm_full::learn(): k-means: iteration:   10   delta: 0.000420035
gmm_full::learn(): k-means: iteration:   11   delta: 0
gmm_full::learn(): EM: n_threads: 8
gmm_full::learn(): EM: iteration:    1   avg_log_p: -2.39245

In [20]:
# print(theta.Pi)
gllim.setParams(theta)


print(gllim.getParamPi())
print(gllim.getParamC())
gllim.train(x_gen, y_gen, 15, 100, 1e-12)
time.sleep(1)
print(gllim.getParamPi()) 
print(gllim.getParamC())

# TODO le gllim.getParamPi() doit changer !


[[0.2 0.2 0.2 0.2 0.2]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
K=5
n_dims=13
n_gaus=5
135
13135
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 895689
gmm_full::learn(): k-means: iteration:    2   delta: 2.05932
gmm_full::learn(): k-means: iteration:    3   delta: 0.528415
gmm_full::learn(): k-means: iteration:    4   delta: 0.13618
gmm_full::learn(): k-means: iteration:    5   delta: 0.0242219
gmm_full::learn(): k-means: iteration:    6   delta: 0.00467005
gmm_full::learn(): k-means: iteration:    7   delta: 0.00537625
gmm_full::learn(): k-means: iteration:    8   delta: 0.00144794
gmm_full::learn(): k-means: iteration:    9   delta: 0.000690363
gmm_full::learn(): k-means: iteration:   10   delta: 0.00017399
gmm_full::learn(): k-means: iteration:   11   delta: 0.000340529
gmm_full::learn(): k-means: iteration:   12   delta: 0.00284367
gmm_full::learn()

In [21]:
print(gllim_parameters.Pi)
print(theta_jgmm.Pi)
print(gllim.getParamPi())

[0.20203492 0.2270894  0.15980739 0.21153459 0.1995337 ]
[[0.32075472 0.32075472 0.32075472 0.01886792 0.01886792]]
[[0.07692308 0.69230769 0.07692308 0.07692308 0.07692308]]
