In [1]:
import newkernelo as lib
import numpy as np
import time

In [2]:
print(lib.__doc__)

model = lib.TestModel()

print(model.__doc__)
print(model.get_D_dimension())
print(model.F.__doc__)
print(model.get_L_dimension())
help(model.F)

# print(lib.TestModel.__doc__)




        Kernelo
        -----------------------
        Functional
        Learning
        DataGeneration
        ...
    

            TestModel
            -----------------------
            derived from Functional
            F(x) = 1/2A*exp(HX) ...
        
9
F(self: newkernelo.TestModel, arg0: Numpy.ndarray[numpy.float64]) -> Numpy.ndarray[numpy.float64]


            Add two numbers
            Some other explanation about the add function.
            

4
Help on method F in module newkernelo:

F(...) method of newkernelo.TestModel instance
    F(self: newkernelo.TestModel, arg0: Numpy.ndarray[numpy.float64]) -> Numpy.ndarray[numpy.float64]
    
    
    Add two numbers
    Some other explanation about the add function.



In [3]:
e = np.exp(1)
x = np.ones(4)

# y = np.zeros(9)
# t0 = time.time()
# for i in range(10000000): #10000000
#     model.F(x,y)
# tf = time.time() - t0
# print("Time F by reference: {}".format(tf))

# t0 = time.time()
# for i in range(10000000):
#     z = model.F(x)
# tf = time.time() - t0
# print("Time F by value: {}".format(tf))

# true_result = np.array([4+2*e, 0.5, e, 3, 0.2, -0.5, -0.2-e, 2*e-1, -0.7])*0.5
# print("true_result")
# print(true_result)

z = model.F(x)
print(z)
print(x)
print(x.shape)
model.to_physic(x)
print(x)
print(x.shape)
w = model.to_physic(x)
print(x)
print(w)
print(w.shape)
print("=========== From physic ==========")
print(x)
model.from_physic(x)
print(x)
y = model.from_physic(x)
print(x)
print(y)
z = model.from_physic(y)
print(x)
print(y)
print(z)

[[ 8.15484549  0.67957046  1.35914091  4.07742274  0.27182818 -0.67957046
  -1.6309691   1.35914091 -0.95139864]]
[1. 1. 1. 1.]
(4,)
[1. 1. 1. 1.]
(4,)
[1. 1. 1. 1.]
[[2. 2. 2. 2.]]
(1, 4)
=========== From physic ==========
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
[1. 1. 1. 1.]
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
[[0.25]
 [0.25]
 [0.25]
 [0.25]]
