In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

(50, 4, 4)


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00797691 0.00786392 0.0076814  ... 0.00802197 0.00833166 0.00801428]
  [0.00778849 0.00784806 0.00759709 ... 0.0079058  0.00803914 0.00777933]
  [0.00797856 0.00788976 0.0080801  ... 0.00778978 0.00768629 0.00761991]
  ...
  [0.00804139 0.00750223 0.00814979 ... 0.00830096 0.00817697 0.007353  ]
  [0.00768335 0.00803118 0.00749531 ... 0.00832178 0.00826581 0.00780015]
  [0.00812498 0.00755848 0.00784295 ... 0.00773187 0.00801998 0.00784677]]

 [[0.00801162 0.00784196 0.00787289 ... 0.00788998 0.00823364 0.00819318]
  [0.00782238 0.00782615 0.00778648 ... 0.00777573 0.00794456 0.007953  ]
  [0.00801328 0.00786773 0.00828154 ... 0.00766161 0.00759586 0.00779002]
  ...
  [0.00807639 0.00748128 0.00835297 ... 0.00816438 0.0080807

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.0372899  0.29172926 0.26123158 0.92824563 0.64921153 0.0048182 ]
 [0.81625425 0.84974065 0.90809895 0.36230468 0.62851595 0.56371093]
 [0.28170547 0.94610638 0.7710181  0.09849416 0.98805942 0.312366  ]
 [0.3392877  0.64790084 0.42644968 0.95929758 0.97673043 0.47626832]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[10.42361196 10.42361196 10.42361196 10.42361196 10.42361196 10.42361196
  10.42361196 10.42361196 10.42361196]
 [14.20643141 14.20643141 14.20643141 14.20643141 14.20643141 14.20643141
  14.20643141 14.20643141 14.20643141]
 [13.10039492 13.10039492 13.10039492 13.10039492 13.10039492 13.10039492
  13.10039492 13.10039492 13.10039492]
 [13.04502615 13.04502615 13.04502615 13.04502615 13.04502615 13.04502615
  13.04502615 13.04502615 13.04502615]
 [15.72755197 15.72755197 15.72755197 15.72755197 15.72755197 15.72755197
  15.72755197 15.72755197 15.72755197]
 [10.07149032 10.07149032 10.07149032 10.07149032 10.07149032 10.07149032
  10.07149032 10.07149032 10.07149032]]
[[[1.07864330e+00 7.98355635e-25 7.98355635e-25 7.98355635e-25
   7.98355635e-25 7.98355635e-25 7.98355635e-25 7.98355635e-25
   7.98355635e-25]
  [7.98355635e-25 1.05812761e+00 7.98355635e-25 7.98355635e-25
   7.98355635e-25 7.98355635e-25 7.98355635e-25 7.98355635e-25
   7.98355635e-25]
  [7.98355635e-25 7.98355635e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.011577844619750977


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.02693653106689453


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.21273182 0.18731891 0.15873547 0.28916379]
 [0.20655751 0.18110299 0.15247309 0.28311416]
 [0.20610971 0.18065243 0.15201896 0.28267529]
 [0.19273479 0.16718767 0.13845334 0.26957035]
 [0.20176277 0.17627629 0.14761004 0.2784161 ]
 [0.20324871 0.17777234 0.14911719 0.27987198]
 [0.19670209 0.17118157 0.1424772  0.27345758]
 [0.19446296 0.16892752 0.14020616 0.27126359]
 [0.18706269 0.16147772 0.13270041 0.26401263]
 [0.19610788 0.17058335 0.1418745  0.27287537]
 [0.18504556 0.15944685 0.13065448 0.26203629]
 [0.21316241 0.18775264 0.15917226 0.28958559]
 [0.19304924 0.16750431 0.13877228 0.2698784 ]
 [0.18433366 0.1587302  0.12993243 0.26133874]
 [0.1855055  0.15990989 0.13112098 0.26248695]
 [0.19776458 0.17225113 0.14355481 0.27449866]
 [0.20312714 0.1776499  0.14899388 0.27975291]
 [0.187649   0.16206783 0.13329504 0.26458715]
 [0.19693298 0.17141425 0.14271142 0.27368371]
 [0.19514592 0.16961494 0.14089882 0.27193283]
 [0.20757968 0.18213212 0.15350986 0.28411567]
 [0.192

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means


Generating dataset
Initializing GLLIM model


INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.673164, Best log likelihood : 25.673164
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.841050


Training model


INFO:root:Iteration : 2, log likelihood : 26.019404
INFO:root:Iteration : 3, log likelihood : 26.126682
INFO:root:Iteration : 4, log likelihood : 26.243889
INFO:root:Iteration : 5, log likelihood : 26.310158
INFO:root:Iteration : 6, log likelihood : 26.341114
INFO:root:Iteration : 7, log likelihood : 26.374105
INFO:root:Iteration : 8, log likelihood : 26.395888
INFO:root:Iteration : 9, log likelihood : 26.423344
INFO:root:Iteration : 10, log likelihood : 26.447281
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01496038 0.00991543 0.01918607 0.01942305 0.01600707 0.00799926
 0.00998594 0.00798545 0.01725202 0.01328357 0.01894852 0.0129992
 0.0313634  0.02987665 0.02302092 0.02496157 0.05119524 0.0229771
 0.01995878 0.01808858 0.01003817 0.0099566  0.01706911 0.02203468
 0.01233403 0.02250366 0.0199539  0.01465181 0.02865267 0.01596882
 0.01181436 0.02927302 0.04216164 0.01110587 0.02891247 0.01237546
 0.02401192 0.03376149 0.01995871 0.0100021  0.01701535 0.01300158
 0.02342299 0.02511509 0.01198728 0.01500268 0.0276824  0.02804697
 0.01997341 0.03282357]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
0.9999999999999999


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(N,L)
Y_gen = np.random.rand(N,D)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00219638 0.00167662 0.00179164 0.00152693 0.00169525 0.00159025]
  [0.00167662 0.00151894 0.00141498 0.0014368  0.00124447 0.00135282]
  [0.00179164 0.00141498 0.00225303 0.00132113 0.00152212 0.00159426]
  [0.00152693 0.0014368  0.00132113 0.00139283 0.00121085 0.00137009]
  [0.00169525 0.00124447 0.00152212 0.00121085 0.00166975 0.00160531]
  [0.00159025 0.00135282 0.00159426 0.00137009 0.00160531 0.00188182]]

 [[0.00221634 0.00147071 0.00179661 0.00162808 0.00213719 0.0019762 ]
  [0.00147071 0.0017764  0.00113376 0.00150051 0.00187328 0.00184155]
  [0.00179661 0.00113376 0.00254434 0.00203228 0.00167649 0.00179522]
  [0.00162808 0.00150051 0.00203228 0.00248968 0.001824   0.00179959]
  [0.00213719 0.00187328 0.00167649 0.001824   0.00257328 0.00233445]
  [0.0019762  0.00184155 0.00179522 0.00179959 0.00233445 0.00229133]]

 [[0.000618   0.00077884 0.0008939  0.00104251 0.00090816 0.00078236]
  [0.00077884 0.00177219 0.00128092 0.

In [27]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
Joint GMM training
K=5
n_dims=36
n_gaus=5
365
36365
gmm_full::learn(): k-means: n_threads: 1
gmm_full::learn(): k-means: recovering from dead means
gmm_full::learn(): k-means: iteration:    1   delta: 86.8189
gmm_full::learn(): k-means: iteration:    2   delta: 0.00348818
gmm_full::learn(): k-means: iteratio

## GLLM training : EM estimator : full/diag

In [28]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [29]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [30]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00388736 0.00266687 0.00254682 0.00190639 0.0023631  0.00249762]
  [0.00266687 0.00217295 0.00204522 0.00135156 0.00133872 0.00154077]
  [0.00254682 0.00204522 0.00237324 0.00145268 0.00129264 0.00150696]
  [0.00190639 0.00135156 0.00145268 0.00138451 0.00132235 0.00144446]
  [0.0023631  0.00133872 0.00129264 0.00132235 0.00193711 0.00173971]
  [0.00249762 0.00154077 0.00150696 0.00144446 0.00173971 0.00232615]]

 [[0.00173657 0.00156074 0.00171046 0.00126317 0.00138707 0.0013618 ]
  [0.00156074 0.00333054 0.00213445 0.00225714 0.00224003 0.00221085]
  [0.00171046 0.00213445 0.00234578 0.0018566  0.00164848 0.00152461]
  [0.00126317 0.00225714 0.0018566  0.00227161 0.00149291 0.00137543]
  [0.00138707 0.00224003 0.00164848 0.00149291 0.00261601 0.00161041]
  [0.0013618  0.00221085 0.00152461 0.00137543 0.00161041 0.00164196]]

 [[0.00223645 0.00175452 0.00130526 0.00136533 0.0005514  0.0017485 ]
  [0.00175452 0.0024188  0.00156753 0.

In [31]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
[[0.5  0.   0.   0.25 0.25]]
GLLiM-EM training
Start GLLiM-EM Training
Iteration : 1, log likelihood : -1239.257218
Iteration : 2, log likelihood : -1452.402658
Iteration : 3, log likelihood : -1665.548098
Iteration : 4, log likelihood : -1878.693537
Iteration : 5, log likelihood : -2091.838977
Iteration : 6, log likelihood : -2304.984417
Iteration : 7, log likelihood : -2518.129856
Iteration : 8, log likelihood : -2732.892777
Iteration : 9, log likelihood : -2953.398273
Iteration : 10, log likelihood : -3178.432797
Iteration : 11, log likelihood : -3403.467321
Iteration : 12, log likelihood : -3628.501845
Iteration : 13, log likelihood : -3853.536369
Iteration : 14, log likelihood : -4078.570893
Iteration : 15, log likelihood : -4303.605417
Iteration : 16, log likelihood : -4528.639941
Iteration : 17, log likelihood : -4753.674465
Iteration : 18, log likelihood : -4978.708989
Iteration : 19, log likelihood : -5203.743513
Iteration : 20, log likelihood : -5428.7