In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>GLLiM Parameters initialized

(50, 4, 4)
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00810307 0.00789029 0.00809169 ... 0.00788297 0.00770242 0.00824177]
  [0.00794298 0.00773506 0.00801201 ... 0.00815284 0.00760585 0.00772733]
  [0.00776851 0.00794122 0.00779004 ... 0.00804262 0.00765252 0.00762931]
  ...
  [0.00771798 0.0080669  0.00801408 ... 0.00752698 0.00758823 0.0082629 ]
  [0.00793959 0.00773506 0.00786951 ... 0.00806967 0.00830291 0.00776798]
  [0.0077108  0.00800195 0.00788515 ... 0.0078652  0.0080504  0.00818333]]

 [[0.00804581 0.00786452 0.00795347 ... 0.0079348  0.00764575 0.0082424 ]
  [0.00788686 0.0077098  0.00787516 ... 0.00820644 0.00754989 0.00772793]
  [0.00771362 0.00791528 0.00765698 ... 0.0080955  0.00759622 0.0076299 ]
  ...
  [0.00766345 0.00804056 0.00787719 ... 0.00757647 0.0075324

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.06870397 0.13229956 0.68577985 0.94531231 0.20507815 0.64245201]
 [0.10926128 0.39879012 0.29342615 0.69158261 0.43813907 0.25064784]
 [0.20527987 0.36851611 0.96412137 0.38398648 0.34605212 0.53358192]
 [0.62323445 0.33437677 0.04167965 0.35728143 0.07991558 0.07224842]]
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[ 9.0194387   9.0194387   9.0194387   9.0194387   9.0194387   9.0194387
   9.0194387   9.0194387   9.0194387 ]
 [ 9.70194768  9.70194768  9.70194768  9.70194768  9.70194768  9.70194768
   9.70194768  9.70194768  9.70194768]
 [11.95502104 11.95502104 11.95502104 11.95502104 11.95502104 11.95502104
  11.95502104 11.95502104 11.95502104]
 [13.13448852 13.13448852 13.13448852 13.13448852 13.13448852 13.13448852
  13.13448852 13.13448852 13.13448852]
 [ 9.20755474  9.20755474  9.20755474  9.20755474  9.20755474  9.20755474
   9.20755474  9.20755474  9.20755474]
 [10.49679055 10.49679055 10.49679055 10.49679055 10.49679055 10.49679055
  10.49679055 10.49679055 10.49679055]]
[[[1.02775487e+00 3.23117427e-27 3.23117427e-27 3.23117427e-27
   3.23117427e-27 3.23117427e-27 3.23117427e-27 3.23117427e-27
   3.23117427e-27]
  [3.23117427e-27 1.07355136e+00 3.23117427e-27 3.23117427e-27
   3.23117427e-27 3.23117427e-27 3.23117427e-27 3.23117427e-27
   3.23117427e-27]
  [3.23117427e-27 3.23117427e-27

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
Time One inversion = 0.014931440353393555


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.031668901443481445HEYYY

HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HEYYY
HE

In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.25278974 0.20474818 0.17613383 0.12953684]
 [0.25399707 0.205971   0.17736585 0.13078384]
 [0.24943313 0.20134854 0.17270853 0.12606976]
 [0.24477278 0.19662846 0.16795287 0.12125617]
 [0.25335412 0.20531989 0.17670983 0.13011986]
 [0.24415276 0.19600049 0.16732016 0.12061574]
 [0.24939048 0.20130541 0.17266508 0.12602582]
 [0.26339444 0.21548888 0.1869555  0.14049037]
 [0.24143953 0.19325251 0.16455147 0.11781333]
 [0.25472671 0.20671003 0.17811045 0.13153753]
 [0.2372723  0.18903183 0.16029897 0.11350901]
 [0.24375682 0.19559951 0.16691617 0.12020686]
 [0.26312559 0.21521657 0.18668113 0.14021265]
 [0.24482973 0.19668612 0.16801096 0.12131495]
 [0.2560678  0.20806832 0.17947899 0.13292279]
 [0.26557658 0.21769901 0.18918229 0.14274431]
 [0.25421046 0.20618712 0.17758361 0.13100427]
 [0.23511139 0.18684318 0.15809381 0.11127695]
 [0.25562877 0.20762368 0.17903099 0.13246932]
 [0.24891334 0.20082214 0.17217817 0.12553298]
 [0.24456714 0.19642023 0.16774306 0.12104381]
 [0.253

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization


Generating dataset
Initializing GLLIM model


INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.671442, Best log likelihood : 25.671442
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.834376


Training model


INFO:root:Iteration : 2, log likelihood : 26.030331
INFO:root:Iteration : 3, log likelihood : 26.138882
INFO:root:Iteration : 4, log likelihood : 26.225769
INFO:root:Iteration : 5, log likelihood : 26.336503
INFO:root:Iteration : 6, log likelihood : 26.380386
INFO:root:Iteration : 7, log likelihood : 26.407645
INFO:root:Iteration : 8, log likelihood : 26.430476
INFO:root:Iteration : 9, log likelihood : 26.454025
INFO:root:Iteration : 10, log likelihood : 26.478324
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01497878 0.01236489 0.01902915 0.01801446 0.01697913 0.0079992
 0.00998571 0.00799085 0.01708383 0.01300324 0.01893786 0.01245787
 0.03221956 0.02942696 0.02261249 0.02495326 0.05473666 0.0229433
 0.01995791 0.01805522 0.0100463  0.00995457 0.01706304 0.02206018
 0.01207213 0.02239365 0.01996278 0.01404218 0.02443745 0.01595825
 0.00999862 0.02881114 0.04130649 0.01264878 0.0285889  0.01156212
 0.0240394  0.03489969 0.02181859 0.0090085  0.01742795 0.01208076
 0.02214683 0.02830327 0.01198995 0.01500272 0.02684822 0.02804783
 0.01998383 0.03376556]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
0.9999999999999999


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00221365 0.00210359 0.00125394 0.00187813 0.00201647 0.00107263]
  [0.00210359 0.00286769 0.00118223 0.0022275  0.00191022 0.0010178 ]
  [0.00125394 0.00118223 0.0013991  0.00152657 0.00122164 0.00074949]
  [0.00187813 0.0022275  0.00152657 0.00267953 0.00191606 0.00136953]
  [0.00201647 0.00191022 0.00122164 0.00191606 0.00242427 0.00112151]
  [0.00107263 0.0010178  0.00074949 0.00136953 0.00112151 0.00079408]]

 [[0.00080529 0.00138486 0.00135443 0.00125443 0.00125994 0.00127737]
  [0.00138486 0.00324486 0.00230354 0.00275655 0.00290154 0.0024632 ]
  [0.00135443 0.00230354 0.0026371  0.00235776 0.00241899 0.00241003]
  [0.00125443 0.00275655 0.00235776 0.00273851 0.00300392 0.0023932 ]
  [0.00125994 0.00290154 0.00241899 0.00300392 0.00339265 0.00256606]
  [0.00127737 0.0024632  0.00241003 0.0023932  0.00256606 0.0029266 ]]

 [[0.00299732 0.00229382 0.001864   0.00214564 0.00099196 0.00210412]
  [0.00229382 0.00190091 0.0014568  0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149655
Iteration : 2, log likelihood : 0.149237
Iteration : 3, log likelihood : 0.149315
Iteration : 4, log likelihood : 0.149314
Iteration : 5, log likelihood : 0.149314
Iteration : 6, log likelihood : 0.149314
Iteration : 7, log likelihood : 0.149314
Iteration : 8, log likelihood : 0.149314
Iteration : 9, log likelihood : 0.149314
Iteration : 10, log likelihood : 0.149314
Maximum iteration number reached
Finish GLLiM-EM Training
	Current log likelihood : 0.149314, Best log likelihood : 0.149314
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Itera

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 1.51637259  0.12616019  0.38825607  0.55973635  0.41668229]
 [ 1.87263505  0.52068549  0.65205282  0.37204696 -0.03426159]
 [ 1.37905093  0.75028931 -0.3456046   0.50978133  0.64603316]
 [ 1.2447546   0.27457435  0.22388813  0.88392749  0.75058537]
 [ 1.97447448 -0.38646546  0.59699804  0.49137405  1.33478647]
 [ 0.15919314  0.53165827  0.8020582   0.0239717   0.51756098]
 [ 0.38163135  0.44593264  0.81922807 -0.10512409 -0.09318494]
 [ 2.07953896  1.20312204  0.77278005  0.59510969 -0.00896055]
 [-1.47144908  0.77618541  0.37392629  0.13258451  0.6352258 ]
 [ 0.3261911   0.56090962  0.26929591  1.30363352 -0.10004139]
 [ 0.16161635  0.39239438  0.21645464  0.92118437  0.46167106]
 [ 0.68995077  0.50459096  0.54949074  0.77676399  0.22429779]
 [ 1.75862444  0.28768214  0.46062305  0.2797964   0.41461371]
 [ 1.21761443  0.69531424  0.50178906  0.25164277  0.85365853]
 [ 1.05528799  0.85511534  0.48345587  0.91642237 -0.04733394]
 [-1.79296636  0.55585171  0.70254637  0.01383287  0.73

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.

Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149655
Iteration : 2, log likelihood : 0.149237
Iteration : 3, log likelihood : 0.149315
Iteration : 4, log likelihood : 0.149314
Iteration : 5, log likelihood : 0.149314
Iteration : 6, log likelihood : 0.149314
Iteration : 7, log likelihood : 0.149314
Iteration : 8, log likelihood : 0.149314
Iteration : 9, log likelihood : 0.149314
Iteration : 10, log likelihood : 0.149314
Maximum iteration number reached
Finish GLLiM-EM Training
	Current log likelihood : 0.149314, Best log likelihood : 0.149314
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train th

## GLLM training : EM estimator : full/diag

In [35]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [36]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [37]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00226465 0.00094605 0.00208836 0.00213504 0.00128935 0.00137619]
  [0.00094605 0.00134505 0.00149066 0.00133416 0.00082249 0.00071289]
  [0.00208836 0.00149066 0.00266926 0.00234963 0.00149093 0.00156651]
  [0.00213504 0.00133416 0.00234963 0.0025791  0.00155131 0.00127278]
  [0.00128935 0.00082249 0.00149093 0.00155131 0.00133935 0.00093678]
  [0.00137619 0.00071289 0.00156651 0.00127278 0.00093678 0.00125974]]

 [[0.0018788  0.00223365 0.00179933 0.00144357 0.00161221 0.00171025]
  [0.00223365 0.00310284 0.00219629 0.00157933 0.00215095 0.00207973]
  [0.00179933 0.00219629 0.00182488 0.00154773 0.00179299 0.00192685]
  [0.00144357 0.00157933 0.00154773 0.00195954 0.00196223 0.0020174 ]
  [0.00161221 0.00215095 0.00179299 0.00196223 0.00252895 0.00225709]
  [0.00171025 0.00207973 0.00192685 0.0020174  0.00225709 0.00257547]]

 [[0.00207105 0.00224199 0.00141154 0.0026298  0.00137691 0.00174288]
  [0.00224199 0.00301315 0.00207207 0.

In [38]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.286183
Iteration : 2, log likelihood : -0.375004
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Training
	Current log likelihood : -inf, Best log likelihood : -inf
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.282085
Iteration : 2, log likelihood : -0.284797
Iteration : 3, log likelihood : -0.334838
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Training
	Current log likelihood : -inf, Best log likelihood : -inf
Initialisation : 3
	Generate GMM means
	Generate GMM covariance m

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
GLLiM-EM training
Start GLLiM-EM Training
Iteration : 1, log likelihood : -inf
Iteration : 2, log likelihood : -inf
Iteration : 3, log likelihood : -inf
Iteration : 4, log likelihood : -inf
Iteration : 5, log likelihood : -inf
Iteration : 6, log likelihood : -inf
Iteration : 7, log likelihood : -inf
Iteration : 8, log likelihood : -inf
Iteration : 9, log likelihood : -inf
Iteration : 10, log likelihood : -inf
Iteration : 11, log likelihood : -inf
Iteration : 12, log likelihood : -inf
Iteration : 13, log likelihood : -inf
Iteration : 14, log likelihood : -inf
Iteration : 15, log likelihood : -inf
Iteration : 16, log likelihood : -inf
Iteration : 17, log likelihood : -inf
Iteration : 18, log likelihood : -inf
Iteration : 19, log likelihood : -inf
Iteration : 20, log likelihood : -inf
Iteration : 21, log likelihood : -inf
Iteration : 22, log likelihood : -inf
Iteration : 23, log likelihood : -inf
Iteration : 24, log likelihood : -inf
Iteration : 25, l

#### Initialize + train GLLiM full/diag from scratch

In [39]:
new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.286183
Iteration : 2, log likelihood : -0.375004
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Training
	Current log likelihood : -inf, Best log likelihood : -inf
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.282085
Iteration : 2, log likelihood : -0.284797
Iteration : 3, log likelihood : -0.334838
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Tra

RuntimeError: gmm_full::set_hefts(): sum of given hefts is not 1