In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

(50, 4, 4)


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00773603 0.00787405 0.00814266 ... 0.00753858 0.00807645 0.00821785]
  [0.00746758 0.00758475 0.00799216 ... 0.00784842 0.00761538 0.00775514]
  [0.00772922 0.00752843 0.00802665 ... 0.00775196 0.00780043 0.00778752]
  ...
  [0.00777006 0.00791348 0.00772665 ... 0.00800229 0.00755308 0.00789381]
  [0.00803838 0.00791669 0.00765921 ... 0.0081384  0.00813893 0.00766643]
  [0.00769385 0.00768455 0.00809296 ... 0.0077296  0.0076561  0.00808479]]

 [[0.00788936 0.00818413 0.00808444 ... 0.00745172 0.00805368 0.00830087]
  [0.00761559 0.00788343 0.00793502 ... 0.00775799 0.00759391 0.00783348]
  [0.0078824  0.0078249  0.00796926 ... 0.00766263 0.00777844 0.00786619]
  ...
  [0.00792405 0.00822511 0.00767141 ... 0.00791009 0.0075317

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.05862875 0.40485969 0.2498631  0.23722734 0.54201332 0.30199176]
 [0.87135994 0.77745906 0.78044149 0.0062369  0.2396793  0.18306794]
 [0.38295305 0.13752628 0.66096795 0.8209777  0.54865092 0.53649047]
 [0.44434722 0.11806472 0.62769266 0.80216347 0.48072424 0.62064375]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[11.27186684 11.27186684 11.27186684 11.27186684 11.27186684 11.27186684
  11.27186684 11.27186684 11.27186684]
 [10.31372926 10.31372926 10.31372926 10.31372926 10.31372926 10.31372926
  10.31372926 10.31372926 10.31372926]
 [12.95689559 12.95689559 12.95689559 12.95689559 12.95689559 12.95689559
  12.95689559 12.95689559 12.95689559]
 [11.59981623 11.59981623 11.59981623 11.59981623 11.59981623 11.59981623
  11.59981623 11.59981623 11.59981623]
 [11.43320333 11.43320333 11.43320333 11.43320333 11.43320333 11.43320333
  11.43320333 11.43320333 11.43320333]
 [10.92658176 10.92658176 10.92658176 10.92658176 10.92658176 10.92658176
  10.92658176 10.92658176 10.92658176]]
[[[1.09361245e+00 1.54616737e-28 1.54616737e-28 1.54616737e-28
   1.54616737e-28 1.54616737e-28 1.54616737e-28 1.54616737e-28
   1.54616737e-28]
  [1.54616737e-28 1.03761686e+00 1.54616737e-28 1.54616737e-28
   1.54616737e-28 1.54616737e-28 1.54616737e-28 1.54616737e-28
   1.54616737e-28]
  [1.54616737e-28 1.54616737e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.0055887699127197266


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.024402379989624023


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.20551868 0.22190968 0.12297548 0.15218858]
 [0.20618212 0.22257027 0.12365336 0.15286135]
 [0.19495294 0.21138959 0.1121799  0.14147435]
 [0.18947781 0.20593811 0.10658567 0.13592227]
 [0.20848765 0.22486583 0.12600904 0.15519928]
 [0.21596411 0.23230999 0.13364814 0.16278082]
 [0.20133001 0.21773911 0.11869569 0.14794104]
 [0.1945346  0.21097306 0.11175246 0.14105013]
 [0.19283879 0.20928457 0.11001976 0.13933048]
 [0.19503047 0.21146678 0.11225912 0.14155297]
 [0.21892148 0.23525459 0.13666984 0.16577976]
 [0.19175825 0.2082087  0.10891572 0.13823476]
 [0.19682786 0.21325641 0.11409561 0.14337562]
 [0.20682394 0.2232093  0.12430914 0.15351219]
 [0.21047804 0.22684762 0.12804272 0.15721764]
 [0.19626343 0.21269442 0.1135189  0.14280326]
 [0.21767528 0.23401377 0.13539653 0.16451604]
 [0.20992061 0.2262926  0.12747317 0.15665238]
 [0.20326839 0.21966911 0.12067624 0.14990666]
 [0.20223926 0.21864443 0.11962472 0.14886307]
 [0.21216935 0.22853163 0.12977084 0.15893273]
 [0.199

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model


Generating dataset
Initializing GLLIM model


INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.687980, Best log likelihood : 25.687980
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.857332


Training model


INFO:root:Iteration : 2, log likelihood : 25.996806
INFO:root:Iteration : 3, log likelihood : 26.094804
INFO:root:Iteration : 4, log likelihood : 26.207344
INFO:root:Iteration : 5, log likelihood : 26.273910
INFO:root:Iteration : 6, log likelihood : 26.313601
INFO:root:Iteration : 7, log likelihood : 26.350457
INFO:root:Iteration : 8, log likelihood : 26.377173
INFO:root:Iteration : 9, log likelihood : 26.395770
INFO:root:Iteration : 10, log likelihood : 26.422677
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01478543 0.01051298 0.01886754 0.02006633 0.01694034 0.00799947
 0.00998492 0.00798431 0.01775467 0.01399968 0.01895143 0.01282651
 0.02805232 0.03010992 0.02281453 0.02493999 0.05197148 0.02294225
 0.01603228 0.01805384 0.0100383  0.00994515 0.01706545 0.0222391
 0.01236832 0.02243328 0.01898228 0.01471844 0.03029101 0.01598977
 0.01194444 0.02948285 0.04129855 0.0119319  0.03091721 0.01198803
 0.02401341 0.03329651 0.01996522 0.00952884 0.01699857 0.01214346
 0.0232677  0.02325179 0.01467135 0.01500099 0.0260776  0.03097185
 0.01997661 0.03361182]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(N,L)
Y_gen = np.random.rand(N,D)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00207287 0.00222414 0.00170827 0.00222998 0.00141901 0.00165704]
  [0.00222414 0.00303206 0.00223956 0.00324206 0.00138094 0.00240228]
  [0.00170827 0.00223956 0.00183358 0.00240258 0.00118412 0.00162909]
  [0.00222998 0.00324206 0.00240258 0.00363364 0.00125035 0.00265876]
  [0.00141901 0.00138094 0.00118412 0.00125035 0.00117447 0.00087299]
  [0.00165704 0.00240228 0.00162909 0.00265876 0.00087299 0.00231602]]

 [[0.00231091 0.00189326 0.00259967 0.00235896 0.00155692 0.00145057]
  [0.00189326 0.00189866 0.00246808 0.00194059 0.00167651 0.00116688]
  [0.00259967 0.00246808 0.0033834  0.00256114 0.00224691 0.00158611]
  [0.00235896 0.00194059 0.00256114 0.0025428  0.00159362 0.00158772]
  [0.00155692 0.00167651 0.00224691 0.00159362 0.00177172 0.00113277]
  [0.00145057 0.00116688 0.00158611 0.00158772 0.00113277 0.0016228 ]]

 [[0.00206136 0.00160532 0.00198102 0.00183421 0.00138108 0.00136274]
  [0.00160532 0.00268214 0.00192716 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149651
Iteration : 2, log likelihood : 0.149472
Iteration : 3, log likelihood : 0.149582
Iteration : 4, log likelihood : 0.149593
Iteration : 5, log likelihood : 0.149593
Iteration : 6, log likelihood : 0.149593
Iteration : 7, log likelihood : 0.149593
Iteration : 8, log likelihood : 0.149593
Iteration : 9, log likelihood : 0.149593
Iteration : 10, log likelihood : 0.149593
Maximum iteration number reached
Finish GLLiM-EM Training
	Current log likelihood : 0.149593, Best log likelihood : 0.149593
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Itera

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 1.86637531e+00  1.62910477e-01  3.30159474e-01  9.58156345e-01
   1.06512783e+00]
 [-1.82791531e-01  4.27458470e-01 -1.76216219e-01  1.14833453e+00
   1.26063671e+00]
 [-3.85974814e-01  4.68553385e-01  9.60992261e-01  1.34917818e-01
  -1.45498658e-01]
 [ 1.24713796e+00 -5.24031251e-02  6.08954199e-01  1.33265505e+00
   1.61689988e+00]
 [ 2.53231648e-01  1.01377904e+00  9.74465318e-02  5.59417469e-01
   3.00468405e-01]
 [ 3.49206060e+00  3.86462284e-01  7.45984405e-02  1.50840050e+00
   7.33881830e-01]
 [-1.10272974e-01  8.78336245e-01  7.74069445e-01 -1.56173758e-02
   3.63931413e-01]
 [ 8.94196088e-01  3.52029063e-01  2.76852242e-03  1.50192050e+00
   9.50854968e-01]
 [ 1.66750949e-01  5.82772332e-01  4.34934188e-01  8.25112008e-01
   5.73253522e-01]
 [ 4.62986194e-01  2.39721704e-01 -4.08676732e-02 -3.63186184e-01
   1.01124182e+00]
 [-3.97750157e-01  7.00269432e-01  7.16904882e-02  3.15714532e-01
   8.61861977e-01]
 [-7.43261291e-01  6.38742602e-01  5.19358660e-01  7.81085574e-01

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]GLLiM Parameters initialized

GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149651
Iteration : 2, log likelihood : 0.149472
Iteration : 3, log likelihood : 0.149582
Iteration : 4, log likelihood : 0.149593
Iteration : 5, log likelihood : 0.149593
Iteration : 6, log likelihood : 0.149593
Iteration : 7, log likelihood : 0.149593
Iteration : 8, log likelihood : 0.149593
Iteration : 9, log likelihood : 0.149593
Iteration : 10, log likelihood : 0.149593
Maximum iteration number reached
Finish GLLiM-EM Training
	Current log likelihood : 0.149593, Best log likelihood : 0.149593
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train th

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00143714 0.00134505 0.00125601 0.0012601  0.00103271 0.00176327]
  [0.00134505 0.00268876 0.0018188  0.00181944 0.00160646 0.00258255]
  [0.00125601 0.0018188  0.00166686 0.00126231 0.00105417 0.00220752]
  [0.0012601  0.00181944 0.00126231 0.00217895 0.00154429 0.0018291 ]
  [0.00103271 0.00160646 0.00105417 0.00154429 0.0016285  0.00163099]
  [0.00176327 0.00258255 0.00220752 0.0018291  0.00163099 0.00300697]]

 [[0.00141707 0.00104729 0.00145006 0.00171127 0.00183076 0.00154354]
  [0.00104729 0.00132267 0.00148911 0.00146315 0.0019026  0.00160847]
  [0.00145006 0.00148911 0.00276691 0.00184631 0.0019182  0.00209949]
  [0.00171127 0.00146315 0.00184631 0.00248472 0.0025141  0.00239146]
  [0.00183076 0.0019026  0.0019182  0.0025141  0.00322326 0.00252127]
  [0.00154354 0.00160847 0.00209949 0.00239146 0.00252127 0.00260542]]

 [[0.00285458 0.00200677 0.00133575 0.00189082 0.00084083 0.00204376]
  [0.00200677 0.00306095 0.00160738 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM


RuntimeError: matrix multiplication: incompatible matrix dimensions: 4x30 and 6x4

In [ ]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]]
GLLiM-EM training
Start GLLiM-EM Training
Iteration : 1, log likelihood : -inf
Iteration : 2, log likelihood : -inf
Iteration : 3, log likelihood : -inf
Iteration : 4, log likelihood : -inf
Iteration : 5, log likelihood : -inf
Iteration : 6, log likelihood : -inf
Iteration : 7, log likelihood : -inf
Iteration : 8, log likelihood : -inf
Iteration : 9, log likelihood : -inf
Iteration : 10, log likelihood : -inf
Iteration : 11, log likelihood : -inf
Iteration : 12, log likelihood : -inf
Iteration : 13, log likelihood : -inf
Iteration : 14, log likelihood : -inf
Iteration : 15, log likelihood : -inf
Iteration : 16, log likelihood : -inf
Iteration : 17, log likelihood : -inf
Iteration : 18, log likelihood : -inf
Iteration : 19, log likelihood : -inf
Iteration : 20, log likelihood : -inf
Iteration : 21, log likelihood : -inf
Iteration : 22, log likelihood : -inf
Iteration : 23, log likelihood : -inf
Iteration : 24, log likelihood : -inf
Iteration : 25, l