In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 3
D = 10
K = 5

gllim = lib.GLLiM(L,D,K)
print(gllim.__doc__)
print(lib.GLLiM.__doc__)
# print(lib.FunctionalModel.__doc__)
# print(lib.ExternalPythonModel.__doc__)
# print(lib.ExternalPythonModel.__init__.__doc__)
help(lib.GLLiM)


            GLLiM class
        GLLiM Parameters initialized


            GLLiM class
        
Help on class GLLiM in module newkernelo:

class GLLiM(pybind11_builtins.pybind11_object)
 |  GLLiM class
 |  
 |  Method resolution order:
 |      GLLiM
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(self: newkernelo.GLLiM, L: int, D: int, K: int) -> None
 |  
 |  getDimensions(...)
 |      getDimensions(self: newkernelo.GLLiM) -> str
 |  
 |  getInverse(...)
 |      getInverse(self: newkernelo.GLLiM) -> newkernelo.GLLiMParameters
 |  
 |  getParamA(...)
 |      getParamA(self: newkernelo.GLLiM) -> Numpy.ndarray[numpy.float64]
 |  
 |  getParamB(...)
 |      getParamB(self: newkernelo.GLLiM) -> Numpy.ndarray[numpy.float64]
 |  
 |  getParamC(...)
 |      getParamC(self: newkernelo.GLLiM) -> Numpy.ndarray[numpy.float64]
 |  
 |  getParamGamma(...)
 |      getParamGamma(self: newkernelo.GLLiM) -> Numpy.

In [3]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
print(theta.L)

[[0. 0. 0. 0. 0.]]
(10, 3, 5)
3


In [4]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=3, D=10, K=5)


In [5]:
gllim.getInverse().C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((L, L, K)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((D, D, K)) * 0.3

gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(Sigma)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]

 [[0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]
  [0.2 0.2 0.2 0.2 0.2]]]
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 

In [7]:
new_theta = lib.GLLiMParameters(L,D,K)

Gamma = np.ones((L,L,K)) + np.random.rand(L,L,K) * 0.1
Sigma = np.ones((D,D,K)) + np.random.rand(D,D,K) * 0.1
for k in range(K):
    Gamma[:,:,k] += np.eye(L) * 0.1
    Gamma[:,:,k] = np.dot(Gamma[:,:,k], Gamma[:,:,k].T) * 0.001
    Sigma[:,:,k] += np.eye(D) * 0.1
    Sigma[:,:,k] = np.dot(Sigma[:,:,k], Sigma[:,:,k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 2
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma

gllim.setParams(new_theta)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[[0.00358005 0.0036683  0.00357596 0.00339522 0.003595  ]
  [0.00358457 0.00357645 0.00357905 0.00341957 0.00362377]
  [0.00354806 0.00360132 0.00357093 0.00337855 0.00348991]]

 [[0.00358457 0.00357645 0.00357905 0.00341957 0.00362377]
  [0.00361954 0.0035184  0.00359886 0.0034666  0.00367415]
  [0.00356975 0.00353051 0.0035769

In [8]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.2 0.2 0.2 0.2 0.2]]
[[[  5.55270139  -3.76917756  -4.08377107 -12.89399261   1.56174281]
  [ -0.98100252   7.80689632   6.1568295    3.09184392  -2.21001477]
  [ -5.27579255   2.83304034   0.54991809   3.10006509   2.10087349]
  [ -4.17145573 -12.56525296 -10.84308295   0.60594768   1.14200373]
  [ -5.22291334  13.43903419   4.41178531  15.91453852   4.10350122]
  [  9.76243588  -7.18018927   1.89692141  -1.38930166   3.93282989]
  [ -4.65244254   5.50847568  10.81078347  -3.91458111   0.71917915]
  [  2.24697708 -10.20547447  -5.76454026  -8.09661716  -1.4924111 ]
  [  2.17659303  -1.29646542  -7.16396349   0.57873084  -6.91068021]
  [  0.72818602   5.5973996    4.19052251   3.16361632  -2.78514875]]

 [[  5.58442045  -3.69247869  -4.094774   -13.03999115   1.57996536]
  [ -0.98660637   7.64803403   6.17341789   3.12685283  -2.23580143]
  [ -5.30592981   2.77539089   0.55139974   3.1351671    2.12538668]
  [ -4.19528461 -12.30956301 -10.87229754   0.61280882   1.15532873]
  [ -5.2

In [10]:
X = np.random.rand(L, 12)

gllim.directDensities(X)

AttributeError: 'newkernelo.GLLiM' object has no attribute 'directDensities'