In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

(50, 4, 4)


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

INFO: GLLiM Parameters initialized


INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00790875 0.00789468 0.00803324 ... 0.00775727 0.00771929 0.00828359]
  [0.00779832 0.00786772 0.00801429 ... 0.00766364 0.00773976 0.0077694 ]
  [0.00745019 0.00771818 0.00792528 ... 0.0080746  0.00788585 0.00758495]
  ...
  [0.00763505 0.00782516 0.00764671 ... 0.0078197  0.00783334 0.00767255]
  [0.00759596 0.00780131 0.00817187 ... 0.00791884 0.00768919 0.00811793]
  [0.00751869 0.00831853 0.00758926 ... 0.00795876 0.00765426 0.00760038]]

 [[0.00815228 0.00760312 0.00813296 ... 0.00771147 0.00765065 0.00826688]
  [0.00803845 0.00757716 0.00811378 ... 0.00761839 0.00767094 0.00775373]
  [0.0076796  0.00743314 0.00802367 ... 0.00802693 0.00781573 0.00756965]
  ...
  [0.00787016 0.00753617 0.00774164 ... 0.00777354 0.0077636

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.82951702 0.91851752 0.24452416 0.65368953 0.14685235 0.39181367]
 [0.90496439 0.96641224 0.95167059 0.71792977 0.44168931 0.45725504]
 [0.79897415 0.33390364 0.51270113 0.46242995 0.28911772 0.18011885]
 [0.20742531 0.10579135 0.6044866  0.70291857 0.84025527 0.77333118]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[14.2226426  14.2226426  14.2226426  14.2226426  14.2226426  14.2226426
  14.2226426  14.2226426  14.2226426 ]
 [12.97387423 12.97387423 12.97387423 12.97387423 12.97387423 12.97387423
  12.97387423 12.97387423 12.97387423]
 [12.94014745 12.94014745 12.94014745 12.94014745 12.94014745 12.94014745
  12.94014745 12.94014745 12.94014745]
 [13.61090345 13.61090345 13.61090345 13.61090345 13.61090345 13.61090345
  13.61090345 13.61090345 13.61090345]
 [11.15374392 11.15374392 11.15374392 11.15374392 11.15374392 11.15374392
  11.15374392 11.15374392 11.15374392]
 [11.40755622 11.40755622 11.40755622 11.40755622 11.40755622 11.40755622
  11.40755622 11.40755622 11.40755622]]
[[[1.06032668e+00 5.67273032e-25 5.67273032e-25 5.67273032e-25
   5.67273032e-25 5.67273032e-25 5.67273032e-25 5.67273032e-25
   5.67273032e-25]
  [5.67273032e-25 1.05285741e+00 5.67273032e-25 5.67273032e-25
   5.67273032e-25 5.67273032e-25 5.67273032e-25 5.67273032e-25
   5.67273032e-25]
  [5.67273032e-25 5.67273032e-25

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.010274171829223633


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.030737638473510742


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.1395625  0.20468698 0.17060217 0.1999665 ]
 [0.13009869 0.19538284 0.16121449 0.19065083]
 [0.14966817 0.21462207 0.18062642 0.20991377]
 [0.15075736 0.21569287 0.18170682 0.21098587]
 [0.1480298  0.21301132 0.17900119 0.20830099]
 [0.14445257 0.20949445 0.17545274 0.20477976]
 [0.15140214 0.21632661 0.18234612 0.2116201 ]
 [0.14711592 0.21211291 0.17809475 0.20740156]
 [0.15091042 0.21584352 0.18185896 0.21113704]
 [0.14065664 0.2057626  0.17168741 0.20104336]
 [0.13951752 0.20464276 0.17055755 0.19992221]
 [0.15148399 0.21640718 0.18242749 0.21170095]
 [0.14208748 0.20716929 0.17310671 0.20245174]
 [0.13486998 0.20007365 0.16594744 0.1953475 ]
 [0.15018984 0.21513499 0.18114397 0.21042741]
 [0.16133329 0.22609038 0.19219769 0.22139628]
 [0.1441101  0.20915784 0.17511317 0.20444288]
 [0.15811963 0.22293091 0.18900983 0.21823286]
 [0.14903386 0.2139985  0.17999726 0.20928947]
 [0.15596247 0.2208102  0.18687012 0.2161096 ]
 [0.132599   0.19784097 0.16369469 0.19311201]
 [0.145

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


Generating dataset
Initializing GLLIM model


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.673393, Best log likelihood : 25.673393
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.827603
INFO:root:Iteration : 2, log likelihood : 25.964465
INFO:root:Iteration : 3, log likelihood : 26.066335


Training model


INFO:root:Iteration : 4, log likelihood : 26.169275
INFO:root:Iteration : 5, log likelihood : 26.233508
INFO:root:Iteration : 6, log likelihood : 26.271838
INFO:root:Iteration : 7, log likelihood : 26.313142
INFO:root:Iteration : 8, log likelihood : 26.354651
INFO:root:Iteration : 9, log likelihood : 26.384033
INFO:root:Iteration : 10, log likelihood : 26.402098
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01482206 0.01002408 0.01830335 0.02396302 0.01598102 0.00799933
 0.00998504 0.00798383 0.01778635 0.01399971 0.01598562 0.01291364
 0.02608057 0.03008592 0.02288435 0.02495376 0.05091156 0.02297365
 0.0169976  0.01811488 0.01002787 0.00995622 0.01706543 0.02219779
 0.01254138 0.022443   0.01896817 0.01463032 0.0305391  0.01595633
 0.0135805  0.02940389 0.04127918 0.01095584 0.03130535 0.01359732
 0.02401031 0.03311597 0.01999931 0.00998604 0.01709628 0.01213827
 0.0231951  0.02457494 0.0146954  0.01500252 0.02623882 0.02900492
 0.01997539 0.03376969]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
0.9999999999999999


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.001956   0.00150892 0.00106281 0.00152973 0.00155818 0.00138   ]
  [0.00150892 0.00203777 0.00101243 0.00117337 0.00132454 0.00115189]
  [0.00106281 0.00101243 0.0011426  0.00080525 0.00116126 0.00090614]
  [0.00152973 0.00117337 0.00080525 0.00139359 0.00119797 0.00123714]
  [0.00155818 0.00132454 0.00116126 0.00119797 0.00177652 0.00129047]
  [0.00138    0.00115189 0.00090614 0.00123714 0.00129047 0.00120825]]

 [[0.00296721 0.00258189 0.00089136 0.00118295 0.00186744 0.00194513]
  [0.00258189 0.00311446 0.00128446 0.00126682 0.00177317 0.002357  ]
  [0.00089136 0.00128446 0.00064444 0.000423   0.00058939 0.00113493]
  [0.00118295 0.00126682 0.000423   0.00111937 0.00057613 0.00105962]
  [0.00186744 0.00177317 0.00058939 0.00057613 0.00148015 0.00127937]
  [0.00194513 0.002357   0.00113493 0.00105962 0.00127937 0.00261425]]

 [[0.00252306 0.00182297 0.00113542 0.00203687 0.00215732 0.00219485]
  [0.00182297 0.00269496 0.00107691 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : 0.149583                                                           
INFO: Iteration : 2, log likelihood : 0.149066                                                           
INFO: Iteration : 3, log likelihood : 0.149371                                                           
INFO: Iteration : 4, log likelihood : 0.149371                                                           
INFO: Iteration : 5, log likelihood : 0.149371                                                           
INFO: Iteration : 6, log likelihood : 0.149371                                                

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 0.71024764  0.57318975  0.698715    0.40444154  0.33406897]
 [ 0.13871397  0.85502161  0.42005579  0.36389972  0.33578303]
 [ 0.47798573  1.29953354  0.72465083  0.50408472  0.73819193]
 [ 0.24002999  0.74933058  0.61497211  0.27783657  1.35066969]
 [ 0.98204302  0.99818311  1.3949149   1.11576487 -0.45863298]
 [-0.0108071   0.42764874  0.16916502  0.33885145  0.10245519]
 [ 0.37960778  0.30284883  0.48300423  0.68595278  1.0261932 ]
 [ 0.05353432  0.55861399  0.82738125  0.41347401  0.02582031]
 [ 0.20707939 -0.25191664  0.73008444  0.8101774   1.19698864]
 [-0.09129377  0.14579902  1.07028663  0.54637095  0.81648716]
 [ 1.14233882  1.14046602  0.19568494  0.19950415 -0.23935428]
 [ 0.54798894  0.22016902  0.60510496 -0.17407914  0.56756856]
 [-0.69973558  0.4044827   0.30179185  1.40037595  0.98843558]
 [-0.31026765  0.6042036   0.67403994  1.11380627  0.23866243]
 [ 0.15101296  0.35382544  0.89274689  0.04744078  0.55579526]
 [ 0.54641494  0.41687137  0.79435834  0.82812434  0.89

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.

INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -inf                                                               
INFO: Iteration : 2, log likelihood : -inf                                                               
INFO: Iteration : 3, log likelihood : -inf                                                               
INFO: Iteration : 4, log likelihood : -inf                                                               
INFO: Iteration : 5, log likelihood : -inf          

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00168917 0.00141589 0.00103036 0.00095732 0.00032035 0.00059638]
  [0.00141589 0.00169575 0.00159132 0.0009289  0.00029436 0.00072577]
  [0.00103036 0.00159132 0.00236795 0.00126662 0.00065951 0.00080548]
  [0.00095732 0.0009289  0.00126662 0.00118396 0.00075475 0.00035927]
  [0.00032035 0.00029436 0.00065951 0.00075475 0.00108085 0.00046548]
  [0.00059638 0.00072577 0.00080548 0.00035927 0.00046548 0.00074623]]

 [[0.00164331 0.00133992 0.00130902 0.0008797  0.0011855  0.00169381]
  [0.00133992 0.0016628  0.00147456 0.00076227 0.00126483 0.00145783]
  [0.00130902 0.00147456 0.00166259 0.00117418 0.00125682 0.00158629]
  [0.0008797  0.00076227 0.00117418 0.00154061 0.00107318 0.00128467]
  [0.0011855  0.00126483 0.00125682 0.00107318 0.00131185 0.00124994]
  [0.00169381 0.00145783 0.00158629 0.00128467 0.00124994 0.00243419]]

 [[0.00180455 0.00135754 0.00111799 0.00162494 0.00167424 0.00104437]
  [0.00135754 0.00197447 0.00129417 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.294675                                                          
INFO: Iteration : 2, log likelihood : -0.309975                                                          
INFO: Iteration : 3, log likelihood : -0.793104                                                          
INFO: Iteration : 4, log likelihood : -6.065398                                                          
INFO: Iteration : 5, log likelihood : -7.351602                                                          
INFO: Iteration : 6, log likelihood : -7.259988                                               

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[7.50000000e-01 2.33435467e-03 1.53219041e-06 3.22542079e-04
  2.47341571e-01]]
[[7.50000000e-01 2.33435467e-03 1.53219041e-06 3.22542079e-04
  2.47341571e-01]]


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized

INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -0.294675                                                          
INFO: Iteration : 2, log likelihood : -0.309975                                                          
INFO: Iteration : 3, log likelihood : -0.793104                                                          
INFO: Iteration : 4, log likelihood : -6.065398                                                          
INFO: Iteration : 5, log likelihood : -7.351602     

In [36]:
import os
import newkernelo as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training                                                                            
INFO: Iteration : 1, log likelihood : -31.694317                                                         
INFO: Iteration : 2, log likelihood : -33.509465                                                         
INFO: Iteration : 3, log likelihood : -113.299547                                                        
INFO: Iteration : 

In [37]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
