In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 4
D = 9
K = 50

gllim = lib.GLLiM(L,D,K, gamma_type='full', sigma_type='diag')
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>
(50, 4, 4)
GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(L,D,K, gamma_type='full', sigma_type='full')

GLLiM Parameters initialized
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00767533 0.0078102  0.00801607 ... 0.00778476 0.00756861 0.00767868]
  [0.00783997 0.00760888 0.00788455 ... 0.00789346 0.00797251 0.00814563]
  [0.00803295 0.00794739 0.00759476 ... 0.00738984 0.00786494 0.00769796]
  ...
  [0.00817821 0.00804024 0.00818424 ... 0.00775398 0.00760861 0.0081122 ]
  [0.00767832 0.00737218 0.0076128  ... 0.00766336 0.00773295 0.00811646]
  [0.00801636 0.00799502 0.00745925 ... 0.00765438 0.00799484 0.00807562]]

 [[0.00774994 0.00797963 0.00808775 ... 0.00799755 0.00774562 0.00748443]
  [0.00791618 0.00777395 0.00795506 ... 0.00810923 0.00815897 0.00793956]
  [0.00811104 0.00811979 0.00766268 ... 0.00759184 0.00804888 0.00750322]
  ...
  [0.00825771 0.00821466 0.00825743 ... 0.00796594 0.0077865

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.53123326 0.87489294 0.43722687 0.61113212 0.46903369 0.29629239]
 [0.75519953 0.17820581 0.8339062  0.87589374 0.65019986 0.61392123]
 [0.65783915 0.8551453  0.78710637 0.53149773 0.99903936 0.23443515]
 [0.36294552 0.85753494 0.62688076 0.6460208  0.01480954 0.44552921]]


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[12.9216524  12.9216524  12.9216524  12.9216524  12.9216524  12.9216524
  12.9216524  12.9216524  12.9216524 ]
 [14.29733697 14.29733697 14.29733697 14.29733697 14.29733697 14.29733697
  14.29733697 14.29733697 14.29733697]
 [14.05536063 14.05536063 14.05536063 14.05536063 14.05536063 14.05536063
  14.05536063 14.05536063 14.05536063]
 [13.99363319 13.99363319 13.99363319 13.99363319 13.99363319 13.99363319
  13.99363319 13.99363319 13.99363319]
 [12.39924735 12.39924735 12.39924735 12.39924735 12.39924735 12.39924735
  12.39924735 12.39924735 12.39924735]
 [10.77053394 10.77053394 10.77053394 10.77053394 10.77053394 10.77053394
  10.77053394 10.77053394 10.77053394]]
[[[1.08227508e+00 2.43865305e-25 2.43865305e-25 2.43865305e-25
   2.43865305e-25 2.43865305e-25 2.43865305e-25 2.43865305e-25
   2.43865305e-25]
  [2.43865305e-25 1.00327654e+00 2.43865305e-25 2.43865305e-25
   2.43865305e-25 2.43865305e-25 2.43865305e-25 2.43865305e-25
   2.43865305e-25]
  [2.43865305e-25 2.43865305e-25

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.00574946403503418


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 0.028091907501220703


In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.14911149 0.27860716 0.12623958 0.1327371 ]
 [0.1538074  0.28312701 0.13096343 0.13745833]
 [0.15441898 0.28368957 0.13157872 0.13808092]
 [0.15064153 0.28006913 0.12777875 0.13427855]
 [0.15502376 0.28422109 0.13218724 0.13870391]
 [0.15238087 0.28174396 0.12952844 0.13602706]
 [0.14936906 0.27881137 0.12649881 0.13300897]
 [0.15601142 0.28522424 0.13318064 0.13968139]
 [0.13988    0.26965646 0.11695334 0.12347511]
 [0.14860065 0.27809311 0.12572577 0.13223011]
 [0.15036623 0.27980098 0.12750182 0.1340027 ]
 [0.16509521 0.29398635 0.14231842 0.14880859]
 [0.1496668  0.27911797 0.12679826 0.1333024 ]
 [0.15267805 0.281999   0.12982748 0.13633501]
 [0.15619849 0.28543568 0.13336873 0.13986019]
 [0.15865715 0.28780593 0.135842   0.14233099]
 [0.14419074 0.27378693 0.12128978 0.12781461]
 [0.14217001 0.27186718 0.11925696 0.12577553]
 [0.15054507 0.27998584 0.1276817  0.13417875]
 [0.14940143 0.2788611  0.12653132 0.13303603]
 [0.15468146 0.2839677  0.13184269 0.13833728]
 [0.153

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization
INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model


Generating dataset
Initializing GLLIM model


INFO:root:	Current log likelihood : 25.671682, Best log likelihood : 25.671682
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.836486
INFO:root:Iteration : 2, log likelihood : 26.009212


Training model


INFO:root:Iteration : 3, log likelihood : 26.147722
INFO:root:Iteration : 4, log likelihood : 26.224432
INFO:root:Iteration : 5, log likelihood : 26.296542
INFO:root:Iteration : 6, log likelihood : 26.349809
INFO:root:Iteration : 7, log likelihood : 26.385641
INFO:root:Iteration : 8, log likelihood : 26.410183
INFO:root:Iteration : 9, log likelihood : 26.426003
INFO:root:Iteration : 10, log likelihood : 26.450199
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(L,D,K, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01412944 0.01173502 0.01904623 0.01801464 0.01695225 0.00799956
 0.0099863  0.00798979 0.01699483 0.01300303 0.01892184 0.01202946
 0.03208223 0.02941922 0.02297952 0.02492144 0.05041839 0.02294018
 0.01996004 0.01803425 0.01005837 0.00991075 0.01706359 0.02294631
 0.01204158 0.02232404 0.01996511 0.014595   0.02816175 0.01694759
 0.00998116 0.02805623 0.04004637 0.01263139 0.02908107 0.0120462
 0.02404882 0.03437455 0.02156373 0.00919861 0.01698514 0.01212884
 0.02300187 0.0256064  0.01487353 0.01500286 0.02820079 0.0280456
 0.01997779 0.03357727]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0000000000000002


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(L,D,K, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
full_full_gllim.setParams(theta_full)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00233347 0.0012746  0.00139781 0.00239726 0.00216458 0.00110412]
  [0.0012746  0.00108925 0.00121595 0.00098751 0.00135494 0.00062341]
  [0.00139781 0.00121595 0.00156141 0.00131641 0.00166039 0.00061522]
  [0.00239726 0.00098751 0.00131641 0.00356255 0.00211567 0.00131077]
  [0.00216458 0.00135494 0.00166039 0.00211567 0.00231271 0.00098413]
  [0.00110412 0.00062341 0.00061522 0.00131077 0.00098413 0.00119218]]

 [[0.00219351 0.00054309 0.00156332 0.00128116 0.00153028 0.0018829 ]
  [0.00054309 0.00038427 0.00081931 0.00068805 0.0005894  0.00100655]
  [0.00156332 0.00081931 0.00238198 0.0017187  0.00146586 0.00243832]
  [0.00128116 0.00068805 0.0017187  0.00152374 0.0009885  0.00176673]
  [0.00153028 0.0005894  0.00146586 0.0009885  0.00165436 0.00191737]
  [0.0018829  0.00100655 0.00243832 0.00176673 0.00191737 0.00310518]]

 [[0.00261417 0.00149315 0.00235024 0.00147797 0.00139123 0.0020498 ]
  [0.00149315 0.00139522 0.00167174 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149652
Iteration : 2, log likelihood : 0.148974
Iteration : 3, log likelihood : 0.149153
Iteration : 4, log likelihood : 0.149173
Iteration : 5, log likelihood : 0.149173
Iteration : 6, log likelihood : 0.149173
Iteration : 7, log likelihood : 0.149173
Iteration : 8, log likelihood : 0.149173
Iteration : 9, log likelihood : 0.149173
Iteration : 10, log likelihood : 0.149173
Maximum iteration number reached
Finish GLLiM-EM Training
0.149173-inf
local_theta Pi
   0.2500   0.1800   0.1600   0.1900   0.2200
best_theta Pi
   0.2500   0.1800   0.1600   0.1900   0.2200
this Pi
   0.2000   0.2000   0.2000   0.2000   0.2000
	Current log likelihood : 0.149173, Best log likelihood : 0.149173
Initialisation : 2
	Gene

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 4.54056534e-01  7.53550845e-01  1.00964723e+00  1.38272859e+00
   1.31166878e-01]
 [ 7.90019453e-01  1.99667662e-01 -9.39621544e-01  8.33972817e-01
   9.90497787e-01]
 [ 9.07091089e-01  5.22681190e-01 -4.66861582e-01  5.81483618e-01
   4.24443794e-01]
 [-1.24375743e+00  1.26191274e+00  4.71265193e-01 -3.68886373e-02
   2.72957256e-01]
 [ 1.41848897e+00  9.60304011e-01  1.91852214e-01  1.16253374e+00
   7.73034687e-01]
 [ 1.48060622e+00  7.15279380e-01  4.03702819e-01  1.70284052e+00
   2.14420167e-01]
 [-6.08406753e-01  7.80054571e-01 -5.25210067e-01 -7.21928146e-02
   1.36810034e-01]
 [ 1.13646973e+00  1.58657345e-01  6.26853470e-01  1.52062083e+00
   2.52270224e-01]
 [-4.16917562e-01  4.22091326e-01 -3.12727633e-01  5.55414507e-01
   1.21991385e+00]
 [ 2.41497839e+00  6.94404192e-01 -1.84187336e-01  2.29570802e-01
   3.81093200e-01]
 [-2.43742521e-04  5.69549044e-01  3.58511830e-01 -1.38861202e-02
   1.45260249e+00]
 [-7.37176096e-01  4.40279923e-01  1.12361812e+00  6.46591048e-01

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.

Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : 0.149652
Iteration : 2, log likelihood : 0.148974
Iteration : 3, log likelihood : 0.149153
Iteration : 4, log likelihood : 0.149173
Iteration : 5, log likelihood : 0.149173
Iteration : 6, log likelihood : 0.149173
Iteration : 7, log likelihood : 0.149173
Iteration : 8, log likelihood : 0.149173
Iteration : 9, log likelihood : 0.149173
Iteration : 10, log likelihood : 0.149173
Maximum iteration number reached
Finish GLLiM-EM Training
0.149173-inf
local_theta Pi
   0.2500   0.1800   0.1600   0.1900   0.2200
best_theta Pi
   0.2500   0.1800   0.1600   0.1900   0.2200
this Pi
       

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(L,D,K, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='diag')
diag_gllim.setParams(new_theta)

GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00260742 0.00166209 0.00159105 0.00155406 0.00189884 0.00108784]
  [0.00166209 0.00165267 0.00144678 0.00105229 0.00162089 0.00116097]
  [0.00159105 0.00144678 0.00202776 0.00104625 0.00205372 0.00116116]
  [0.00155406 0.00105229 0.00104625 0.00102229 0.00128692 0.00065441]
  [0.00189884 0.00162089 0.00205372 0.00128692 0.0023484  0.00135002]
  [0.00108784 0.00116097 0.00116116 0.00065441 0.00135002 0.00112708]]

 [[0.00122625 0.00118633 0.00102491 0.00151828 0.00123572 0.0011338 ]
  [0.00118633 0.00162166 0.00138319 0.00186222 0.00129709 0.00122843]
  [0.00102491 0.00138319 0.00175694 0.00228326 0.00151543 0.00096087]
  [0.00151828 0.00186222 0.00228326 0.00337653 0.00196483 0.00151481]
  [0.00123572 0.00129709 0.00151543 0.00196483 0.00189151 0.00102162]
  [0.0011338  0.00122843 0.00096087 0.00151481 0.00102162 0.00114497]]

 [[0.00190895 0.0018811  0.00131049 0.00195663 0.00134034 0.00179062]
  [0.0018811  0.00235858 0.00202295 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.288840
Iteration : 2, log likelihood : -0.351856
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Training
-inf-inf
local_theta Pi
   0.2124   0.3360   0.1438   0.1739   0.1340
best_theta Pi
   0.2124   0.3360   0.1438   0.1739   0.1340
this Pi
   0.2000   0.2000   0.2000   0.2000   0.2000
	Current log likelihood : -inf, Best log likelihood : -inf
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.283306
Iteration : 2, log likelihood : -0.285991
Iteration : 3, log likelihood : -0.314179
Likelihood inc

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
print(diag_gllim.getParamPi())

[[0.25697225 0.05808576 0.16777838 0.06965627 0.44750734]]
[[4.99551379e-01 1.97641642e-16 4.48621282e-04 3.42617233e-14
  5.00000000e-01]]
GLLiM-EM training
Start GLLiM-EM Training
Iteration : 1, log likelihood : -8.556810
Iteration : 2, log likelihood : -17.332469
Likelihood increase threshold reached :0.000010
Finish GLLiM-EM Training


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(L,D,K,gamma_type='full', sigma_type='full')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]
GLLiM Parameters initialized
GLLiM dimensions are (L=6, D=30, K=5)
GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.
Start Initialization
Initialisation : 1
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration : 1, log likelihood : -0.288840
Iteration : 2, log likelihood : -0.351856
Likelihood increase threshold reached :-0.010000
Finish GLLiM-EM Training
-inf-inf
local_theta Pi
   0.2124   0.3360   0.1438   0.1739   0.1340
best_theta Pi
   0.2124   0.3360   0.1438   0.1739   0.1340
this Pi
        0        0        0        0        0
	Current log likelihood : -inf, Best log likelihood : -inf
Initialisation : 2
	Generate GMM means
	Generate GMM covariance matrices
	Train the GMM model
	Compute Initial theta vector of the GLLiM model from GMM
	Train the initial GLLiM model
Start GLLiM-EM Training
Iteration 