In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
L = 30
D = 100
K = 50

gllim = lib.GLLiM(L,D,K)
print(gllim.__doc__)
print(lib.GLLiM.__doc__)
# print(lib.FunctionalModel.__doc__)
# print(lib.ExternalPythonModel.__doc__)
# print(lib.ExternalPythonModel.__init__.__doc__)
help(lib.GLLiM)


            GLLiM class
        GLLiM Parameters initialized


            GLLiM class
        
Help on class GLLiM in module newkernelo:

class GLLiM(pybind11_builtins.pybind11_object)
 |  GLLiM class
 |  
 |  Method resolution order:
 |      GLLiM
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(self: newkernelo.GLLiM, L: int, D: int, K: int) -> None
 |  
 |  directDensities(...)
 |      directDensities(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64], arg1: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |      
 |      2. directDensities(self: newkernelo.GLLiM, arg0: Numpy.ndarray[numpy.float64]) -> newkernelo.PredictionResult
 |  
 |  getDimensions(...)
 |      getDimensions(self: newkernelo.GLLiM) -> str
 |  
 |  getInverse(...)
 |      getInverse(self: newkernelo.GLLiM) -> newkernelo.GLL

In [3]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
print(theta.L)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(100, 30, 50)
30


In [4]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=30, D=100, K=50)


In [5]:
gllim.getInverse().C

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((L, L, K)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((D, D, K)) * 0.3

gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(Sigma)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]


In [7]:
new_theta = lib.GLLiMParameters(L,D,K)

Gamma = np.ones((L,L,K)) + np.random.rand(L,L,K) * 0.1
Sigma = np.ones((D,D,K)) + np.random.rand(D,D,K) * 0.1
for k in range(K):
    Gamma[:,:,k] += np.eye(L) * 0.1
    Gamma[:,:,k] = np.dot(Gamma[:,:,k], Gamma[:,:,k].T) * 0.001
    Sigma[:,:,k] += np.eye(D) * 0.1
    Sigma[:,:,k] = np.dot(Sigma[:,:,k], Sigma[:,:,k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 2
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma

gllim.setParams(new_theta)

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  ...
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]]

 [[2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  ...
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]]

 [[2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  ...
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]]

 ...

 [[2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  ...
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]]

 [[2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]
  [2. 2. 2. ... 2. 2. 2.]


In [8]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[ 0.5434155  -0.03532858  0.39002588 ...  0.00818671  1.92833122
    0.05018591]
  [-1.21986284  0.07272733  0.54335764 ...  0.25873999  1.70802454
   -0.19180404]
  [ 0.29921842 -0.11555966 -0.68620414 ...  0.88889072 -1.36431976
    0.02292923]
  ...
  [-0.33469623  0.07697725  0.40239206 ...  0.29479953 -1.74050773
    0.10238152]
  [-0.22088182  0.29222361 -2.38028437 ... -1.32727265  0.73715939
    0.01102686]
  [-0.18715531 -0.10565546 -1.08529447 ...  0.06725017  0.90614474
    0.19615976]]

 [[ 0.54840716 -0.03546348  0.39170063 ...  0.00817904  1.94233941
    0.05028347]
  [-1.23106815  0.07300501  0.54569079 ...  0.25849769  1.72043233
   -0.19217692]
  [ 0.30196696 -0.11600089 -0.68915066 ...  0.88805831 -1.37423074
 

In [9]:
x = np.random.rand(L, 2)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[0.08817772 0.65756104]
 [0.30092924 0.58234343]
 [0.47908224 0.76869033]
 [0.79890561 0.91276758]
 [0.85203353 0.70206851]
 [0.92051596 0.96390796]
 [0.05841048 0.53924668]
 [0.98155775 0.31943152]
 [0.58850585 0.82982877]
 [0.70164405 0.44710535]
 [0.84813079 0.64707329]
 [0.84697673 0.87986184]
 [0.72709418 0.70961521]
 [0.68026371 0.70919367]
 [0.78725773 0.1854741 ]
 [0.28903206 0.27914396]
 [0.5523258  0.25849441]
 [0.22194633 0.78348794]
 [0.7580366  0.12343341]
 [0.43307656 0.45463304]
 [0.07973905 0.80835403]
 [0.34262521 0.80928668]
 [0.04053784 0.4264191 ]
 [0.33975475 0.60493545]
 [0.93572794 0.2294633 ]
 [0.86907507 0.72566511]
 [0.2556836  0.89301537]
 [0.64042953 0.18576134]
 [0.21243427 0.61050557]
 [0.55387804 0.8430395 ]]


In [10]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 38.36757642 38.36757642 38.36757642
  38.36757642 38.36757642 38.36757642 

In [11]:
y = np.random.rand(D, 400)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.34401464462280273


In [12]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [13]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,400)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

Time Multi inversion = 28.51272487640381


In [14]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.isclose(prediction_results.meanPredResult.mean == prediction_results_all.meanPredResult.mean))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[ 0.05821937  0.0887816   0.08456384 ...  0.06007759  0.06151345
   0.14877529]
 [-0.05270211 -0.07656106 -0.02993341 ... -0.0473442  -0.04451753
  -0.08211227]
 [ 0.05465097  0.01461514 -0.00357779 ...  0.04138548  0.02635515
   0.00607432]
 ...
 [-0.00587399 -0.04476318 -0.01707889 ...  0.00052898 -0.06919649
  -0.05319116]
 [-0.03926795 -0.01862082 -0.01472245 ... -0.00989314 -0.01578494
   0.00267992]
 [-0.16671456 -0.17836651 -0.24512665 ... -0.19017972 -0.17914178
  -0.23387706]]
[[ 0.05821937  0.0887816   0.08456384 ...  0.06007759  0.06151345
   0.14877529]
 [-0.05270211 -0.07656106 -0.02993341 ... -0.0473442  -0.04451753
  -0.08211227]
 [ 0.05465097  0.01461514 -0.00357779 ...  0.04138548  0.02635515
   0.00607432]
 ...
 [-0.00587399 -0.04476318 -0.01707889 ...  0.00052898 -0.06919649
  -0.05319116]
 [-0.03926795 -0.01862082 -0.01472245 ... -0.00989314 -0.01578494
   0.00267992]
 [-0.16671456 -0.17836651 -0.24512665 ... -0.19017972 -0.17914178
  -0.23387706]]


TypeError: isclose() missing 1 required positional argument: 'b'