In [1]:
import newkernelo as lib
import kernelo as oldker
import numpy as np
import time
import os.path
import json
import logging
logging.getLogger().setLevel(logging.INFO)

In [2]:
K = 50
D = 9
L = 4

# ! Hybrid model
n_hidden_variables = 0
L_t = L - n_hidden_variables
L_w = n_hidden_variables

gllim = lib.GLLiM(K, D, L, gamma_type='full', sigma_type='diag', n_hidden_variables=n_hidden_variables)
print(type(gllim))
gllim.getDimensions()
gllim.getConstraints()
gllim.getParamPi()
gllim.getParamGamma()
print(gllim.getParamGamma().shape)


<class 'newkernelo._GLLiM_full_diag'>INFO: GLLiM Parameters initialized

(50, 4, 4)
INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [3]:
lib._GLLiM_full_diag(K, D, L, 'full', 'full', n_hidden_variables)

INFO: GLLiM Parameters initialized


INFO: GLLiM dimensions are (L=4, D=9, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [4]:
print(gllim.getDimensions())
gllim.getParams()
gllim.getParamGamma().shape

GLLiM dimensions are (L=4, D=9, K=50)


(50, 4, 4)

In [5]:
theta = gllim.getParams()
print(theta.Pi)
print(theta.A.shape)
# print(theta.L)
print(gllim.getDimensions())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]
(9, 4, 50)
GLLiM dimensions are (L=4, D=9, K=50)


In [6]:
gllim.getParams()
gllim.getParamPi()
gllim.getParamA()
gllim.getParamC()
gllim.getParamGamma()
gllim.getParamB()
gllim.getParamSigma()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [7]:
gllim.getInverse().C
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)


In [8]:
Pi = np.ones(K) * 1 / K
A = np.ones((D, L, K))
C = np.ones((L, K)) * 2
Gamma = np.ones((K,L, L)) * 0.2
B = np.ones((D, K)) * 3
Sigma = np.ones((K,D, D)) * 0.3
print(Gamma.shape)
gllim.setParamPi(Pi)
gllim.setParamA(A)
gllim.setParamC(C)
gllim.setParamGamma(Gamma)
gllim.setParamB(B)
gllim.setParamSigma(np.array(Sigma[:,:,0]))

theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)
print(theta.Sigma.shape)
print(gllim.getDimensions())

(50, 4, 4)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2.

In [9]:
print(gllim.getDimensions())
gllim.getParams()
print(gllim.getDimensions())

GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)


In [10]:
new_theta = lib.GLLiMParameters(K,D,L, "full", "diag")
print(type(new_theta))

Gamma = np.ones((K,L,L)) + np.random.rand(K,L,L) * 0.1
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k] += np.eye(L) * 0.1
    Gamma[k] = np.dot(Gamma[k], Gamma[k].T) * 0.001
    # Sigma[k] += np.eye(D) * 0.1
    # Sigma[k] = np.dot(Sigma[k], Sigma[k].T) * 0.001
new_theta.Pi = Pi
new_theta.A = A * 3
new_theta.C = C * 2
new_theta.Gamma = Gamma
new_theta.B = B * 2
new_theta.Sigma = Sigma
print(gllim.getDimensions())
gllim.setParams(new_theta)
print(gllim.getDimensions()) # TODO ERROR GLLiM<TGamma,TSigma> dimensions are (L=4000838736, D=32766, K=4000837888)
theta = gllim.getParams()
print(theta.Pi)
print(theta.A)
print(theta.C)
print(theta.Gamma)
print(theta.B)
print(theta.Sigma)

<class 'newkernelo._GLLiMParameters_full_diag'>
GLLiM dimensions are (L=4, D=9, K=50)
GLLiM dimensions are (L=4, D=9, K=50)
[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  

In [11]:
theta_star = gllim.getInverse()

print(theta_star.Pi)
print(theta_star.A)
print(theta_star.C)
print(theta_star.Gamma)
print(theta_star.B)
print(theta_star.Sigma)

[[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
  0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]]
[[[0.00810951 0.00788183 0.00806074 ... 0.00782451 0.00802758 0.00767968]
  [0.00792537 0.00757301 0.00783609 ... 0.00827048 0.00803246 0.00805738]
  [0.00783945 0.00804149 0.00767482 ... 0.00778384 0.00807739 0.00765052]
  ...
  [0.00767529 0.00765608 0.00814087 ... 0.00834243 0.00777491 0.00805437]
  [0.00834131 0.00770035 0.00790478 ... 0.00822379 0.00768657 0.00783816]
  [0.0079324  0.00800446 0.00778036 ... 0.00817856 0.00757648 0.00766217]]

 [[0.00805789 0.00781615 0.00819599 ... 0.00765252 0.00801351 0.00764664]
  [0.00787493 0.0075099  0.00796758 ... 0.00808868 0.00801838 0.00802272]
  [0.00778955 0.00797447 0.0078036  ... 0.00761274 0.00806323 0.0076176 ]
  ...
  [0.00762644 0.00759228 0.00827747 ... 0.00815906 0.0077612

In [12]:
x = np.random.rand(L, 6)
x_incertitudes = np.random.rand(L) * 0.2
print(x)
prediction_direct_results = gllim.directDensities(x, x_incertitudes)

[[9.47844289e-01 1.56376509e-01 8.21759712e-01 4.95048850e-01
  1.41455091e-01 9.94255528e-01]
 [8.13217312e-01 4.76008443e-01 9.47109112e-01 7.75855722e-01
  6.27745499e-01 5.67984235e-01]
 [8.64747095e-01 6.45428996e-01 9.70116161e-01 1.99442637e-04
  6.29404952e-01 5.90830612e-01]
 [7.49966584e-01 6.75810598e-01 9.54724690e-01 7.81494299e-01
  8.22068908e-01 2.29221333e-02]]
INFO: Alter theta covariance
INFO: Construct the GMM of the forward conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [13]:
print(prediction_direct_results.meanPredResult.mean)
print(prediction_direct_results.meanPredResult.variance)
print(prediction_direct_results.meanPredResult.gmm_weights)
print(prediction_direct_results.meanPredResult.gmm_means)

[[16.12732584 16.12732584 16.12732584 16.12732584 16.12732584 16.12732584
  16.12732584 16.12732584 16.12732584]
 [11.86087364 11.86087364 11.86087364 11.86087364 11.86087364 11.86087364
  11.86087364 11.86087364 11.86087364]
 [17.08112902 17.08112902 17.08112902 17.08112902 17.08112902 17.08112902
  17.08112902 17.08112902 17.08112902]
 [12.15779494 12.15779494 12.15779494 12.15779494 12.15779494 12.15779494
  12.15779494 12.15779494 12.15779494]
 [12.66202335 12.66202335 12.66202335 12.66202335 12.66202335 12.66202335
  12.66202335 12.66202335 12.66202335]
 [12.52797752 12.52797752 12.52797752 12.52797752 12.52797752 12.52797752
  12.52797752 12.52797752 12.52797752]]
[[[1.00080575e+00 1.13911515e-25 1.13911515e-25 1.13911515e-25
   1.13911515e-25 1.13911515e-25 1.13911515e-25 1.13911515e-25
   1.13911515e-25]
  [1.13911515e-25 1.06691766e+00 1.13911515e-25 1.13911515e-25
   1.13911515e-25 1.13911515e-25 1.13911515e-25 1.13911515e-25
   1.13911515e-25]
  [1.13911515e-25 1.13911515e-2

In [14]:
y = np.random.rand(D, 40)
y_incertitudes = np.random.rand(D,1) * 0.01
# print(y)
# print(y_incertitudes)
tic = time.time()
prediction_results = gllim.inverseDensities(y, y_incertitudes)
print("Time One inversion = {}".format(time.time()-tic))

Time One inversion = 0.007693290710449219
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture


In [15]:
# print(prediction_results.meanPredResult.mean)
# print(prediction_results.meanPredResult.variance)
# print(prediction_results.meanPredResult.gmm_weights)
# print(prediction_results.meanPredResult.gmm_means)

In [16]:
import numpy.matlib
y_incertitudes_temp = np.matlib.repmat(y_incertitudes,1,40)
y_incertitudes_mat = np.copy(y_incertitudes_temp)
# y_incertitudes_mat = np.random.rand(D, 4) * 0.01
# print(y_incertitudes_mat)
tic = time.time()
prediction_results_all = gllim.inverseDensities(y, y_incertitudes_mat)
print("Time Multi inversion = {}".format(time.time()-tic))

INFO: Alter theta covarianceTime Multi inversion = 0.030395984649658203

INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO: Alter theta covariance
INFO: Inverse theta
INFO: Construct the GMM of the inverse conditional model
INFO: Compute the weighted mean of the means in the mixture
INFO: Compute the weighted covariance of the covariances in the mixture
INFO

In [17]:
print("\nmean")
print(prediction_results_all.meanPredResult.mean)
print(prediction_results.meanPredResult.mean)
print(np.all(np.isclose(prediction_results.meanPredResult.mean, prediction_results_all.meanPredResult.mean)))
# print("\nvariance")
# print(prediction_results_all.meanPredResult.variance)
# print(prediction_results_all.meanPredResult.gmm_weights)
# print(prediction_results_all.meanPredResult.gmm_means)


mean
[[0.17838104 0.28636444 0.14766648 0.18072199]
 [0.16602566 0.27607684 0.13387763 0.16933188]
 [0.17165254 0.28152523 0.13950705 0.17496422]
 [0.18936049 0.29596617 0.15967633 0.19106592]
 [0.17940373 0.28221257 0.15287441 0.17882114]
 [0.19477815 0.30422412 0.16263816 0.19820237]
 [0.18806674 0.29643798 0.1569659  0.19075439]
 [0.18345357 0.29307787 0.15137013 0.18679442]
 [0.16334549 0.27066669 0.13336919 0.16508716]
 [0.17354692 0.28420202 0.1408202  0.17730546]
 [0.17303401 0.28071539 0.14260582 0.17513285]
 [0.17997106 0.29179936 0.14623596 0.18448389]
 [0.18294    0.29283    0.15071859 0.18640154]
 [0.17736074 0.28471724 0.14719304 0.17932827]
 [0.18593773 0.29806217 0.15193428 0.19069195]
 [0.17373079 0.27564383 0.14782523 0.17260989]
 [0.16706307 0.2768429  0.13512829 0.1702287 ]
 [0.16829478 0.2764042  0.13767169 0.17053839]
 [0.19485438 0.30074336 0.16564593 0.19624351]
 [0.17727591 0.28374837 0.14778776 0.17874532]
 [0.18332377 0.29055186 0.15299639 0.1853607 ]
 [0.175

# GLLiM TRAIN

In [18]:
# Create "physical" model
# dir_path = os.path.dirname(os.path.realpath(__file__))
# print(dir_path+"/pytest/models")
# physical_model = oldker.ExternalModelConfig("RPVModel", "rpv_model", dir_path + "/pytest/models").create()
physical_model = oldker.TestModelConfig().create()

# Create StatModel
covariances = np.random.uniform(0, 0.0001, physical_model.get_D_dimension())
stat_model = oldker.GaussianStatModelConfig("sobol", physical_model, covariances, 12345).create()

# Create GLLIM model, including its initialization and training configuration
learningConfig = oldker.EMLearningConfig(10, 1e-5, 1e-12)
# learningConfig=oldker.GMMLearningConfig(15, 100, 1e-12)
# initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=10, gmmLearningConfig=oldker.GMMLearningConfig(15, 10, 1e-12))
initConfig = oldker.MultInitConfig(seed=123456789, nb_iter_EM=10, nb_experiences=1, gmmLearningConfig=oldker.GMMLearningConfig(0, 0, 1e-12))
gllim_oldker= oldker.GLLiM(physical_model.get_D_dimension(), physical_model.get_L_dimension(), 50, "Full", "Diag", initConfig, learningConfig)


In [19]:
# Initialize and train GLLIM model
print("Generating dataset")
x_gen, y_gen = stat_model.gen_data(1000)
print("Initializing GLLIM model")
gllim_oldker.initialize(x_gen, y_gen)
gllim_parameters_0 = gllim_oldker.exportModel() # you can export your gllim model parameters
print("Training model")
gllim_oldker.train(x_gen, y_gen)

gllim_parameters = gllim_oldker.exportModel() # you can export your gllim model parameters


INFO:root:Start Multi initialization


Generating dataset
Initializing GLLIM model


INFO:root:Initialisation : 1
INFO:root:	Generate GMM means
INFO:root:	Generate GMM covariance matrices
INFO:root:	Train the GMM model
INFO:root:	Compute Initial theta vector of the GLLiM model
INFO:root:	Train the initial GLLiM model
INFO:root:	Current log likelihood : 25.695468, Best log likelihood : 25.695468
INFO:root:Finish Multi initialization
INFO:root:Start GLLiM-EM Training
INFO:root:Iteration : 1, log likelihood : 25.845252
INFO:root:Iteration : 2, log likelihood : 25.988927
INFO:root:Iteration : 3, log likelihood : 26.096361


Training model


INFO:root:Iteration : 4, log likelihood : 26.225660
INFO:root:Iteration : 5, log likelihood : 26.295574
INFO:root:Iteration : 6, log likelihood : 26.333513
INFO:root:Iteration : 7, log likelihood : 26.374714
INFO:root:Iteration : 8, log likelihood : 26.401022
INFO:root:Iteration : 9, log likelihood : 26.411802
INFO:root:Iteration : 10, log likelihood : 26.426418
INFO:root:Maximum iteration number reached
INFO:root:Finish GLLiM-EM Training


### Get theta_0 from oldker

In [20]:
theta_0 = lib.GLLiMParameters(K,D,L, "full", "diag")

print(np.array(gllim_parameters_0.Pi).shape)
print(np.array(gllim_parameters_0.A).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.array(gllim_parameters_0.Gamma).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.array(gllim_parameters_0.Sigma).shape)

print(np.array(gllim_parameters_0.Pi))
print(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)).shape)
print(np.array(gllim_parameters_0.C).shape)
print(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)).shape)
print(np.array(gllim_parameters_0.B).shape)
print(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)).shape)

theta_0.Pi = np.copy(np.array(gllim_parameters_0.Pi))
theta_0.A = np.copy(np.transpose(np.array(gllim_parameters_0.A), (1,2,0)))
theta_0.C = np.copy(np.array(gllim_parameters_0.C))
# theta_0.Gamma = np.copy(np.transpose(np.array(gllim_parameters_0.Gamma), (1,2,0)))
theta_0.Gamma = np.copy(gllim_parameters_0.Gamma)
theta_0.B = np.copy(np.array(gllim_parameters_0.B))
# theta_0.Sigma = np.copy(np.transpose(np.array(gllim_parameters_0.Sigma), (1,2,0)))
Sigma_diag = np.zeros((K,D))
for k in range(K):
    Sigma_diag[k,:] = np.diag(gllim_parameters_0.Sigma[k])
theta_0.Sigma = Sigma_diag

print(np.sum(theta_0.Pi))
gllim.setParams(theta_0)

(50,)
(50, 9, 4)
(4, 50)
(50, 4, 4)
(9, 50)
(50, 9, 9)
[0.01482544 0.01123806 0.01857775 0.02396376 0.01598458 0.00799932
 0.00998517 0.007984   0.01780531 0.01399971 0.01890671 0.01263352
 0.02608057 0.03008255 0.02297907 0.02476309 0.05266481 0.02297269
 0.01996534 0.01808732 0.01001942 0.00971746 0.01706561 0.02221611
 0.01249218 0.02237071 0.01896723 0.01371883 0.02716069 0.01598564
 0.01200894 0.03043409 0.04129975 0.01095257 0.02999205 0.01255342
 0.02401678 0.03324678 0.01928827 0.00906092 0.0174662  0.01213913
 0.02335522 0.02478599 0.01456099 0.01500269 0.02659781 0.02914062
 0.01997672 0.03290841]
(9, 4, 50)
(4, 50)
(4, 4, 50)
(9, 50)
(9, 9, 50)
1.0


In [21]:
# theta_0 = theta
# print(theta_0.Pi)
# print(theta_0.C)

# jgmm = lib.JGMM()
# theta_jgmm = jgmm.train(x_gen, y_gen, theta_0, 15, 10, 1e-12)
# print(theta_0.Pi)
# print(theta_jgmm.Pi)
# print(theta_0.C)
# print(theta_jgmm.C)

# TODO ça plante parceque le V (dans jgmm.cpp) n'est pas sym strict def positif. Surement que dans gllim_parameters_0 a un Gamma et Sigma qui n'est pas sym strict def positif

In [22]:
# # print(theta.Pi)
# gllim.setParams(theta)


# # print(gllim.getParamPi())
# # print(gllim.getParamC())
# gllim.train(x_gen, y_gen, 15, 100, 1e-12)
# time.sleep(1)
# print(gllim.getParamPi()) 
# print(gllim.getParamC())

# # TODO le gllim.getParamPi() doit changer !


In [23]:
# print(gllim_parameters.Pi)
# print(theta_jgmm.Pi)
# print(gllim.getParamPi())

## GLLM training : EM estimator : full/full

In [24]:
L, D, K, N = 6, 30, 5, 100
theta_full = lib.GLLiMParameters(K,D,L, "full", "full")

Gamma = np.random.rand(K,L,L)
Sigma = np.random.rand(K,D,D)
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    Sigma[k,:,:] += np.eye(D) * 0.1
    Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
theta_full.Pi = np.ones(K) * 1 / K
theta_full.A = np.ones((D, L, K)) * 0.3
theta_full.C = np.ones((L, K)) * 0.2
theta_full.Gamma = Gamma
theta_full.B = np.ones((D, K)) * 0.5
theta_full.Sigma = Sigma

X_gen = np.random.rand(L,N) # TODO transpose X,Y in the python bindings in order to use the transposed version in Python (row-major)
Y_gen = np.random.rand(D,N)

In [25]:
L_t = L
full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
full_full_gllim.setParams(theta_full)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.


In [26]:
print(theta_full.Pi)
print(full_full_gllim.getParamPi())
print(full_full_gllim.getParamGamma())
print(theta_full.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00131683 0.00077224 0.00143758 0.00127574 0.00175476 0.00118123]
  [0.00077224 0.00090766 0.00109341 0.00101678 0.00139195 0.0009725 ]
  [0.00143758 0.00109341 0.00254389 0.00142293 0.00202879 0.00189077]
  [0.00127574 0.00101678 0.00142293 0.00163074 0.00200783 0.00123892]
  [0.00175476 0.00139195 0.00202879 0.00200783 0.00288724 0.00173302]
  [0.00118123 0.0009725  0.00189077 0.00123892 0.00173302 0.00147337]]

 [[0.00237946 0.00090772 0.00179337 0.00130422 0.00225396 0.00118507]
  [0.00090772 0.00070443 0.00088019 0.00097555 0.00103722 0.00074684]
  [0.00179337 0.00088019 0.00230087 0.0012037  0.0021543  0.00094521]
  [0.00130422 0.00097555 0.0012037  0.00203026 0.00189769 0.00117412]
  [0.00225396 0.00103722 0.0021543  0.00189769 0.00294412 0.0013783 ]
  [0.00118507 0.00074684 0.00094521 0.00117412 0.0013783  0.00095833]]

 [[0.00331878 0.00144397 0.0031888  0.00279946 0.00188899 0.00223327]
  [0.00144397 0.00074295 0.00142455 0.

In [27]:
print(full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(full_full_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.994533
INFO: Iteration : 2, log likelihood : 2.986467
INFO: Iteration : 3, log likelihood : 2.990063
INFO: Iteration : 4, log likelihood : 2.991853
INFO: Iteration : 5, log likelihood : 2.991853
INFO: Iteration : 6, log likelihood : 2.991853
INFO: Iteration : 7, log likelihood : 2.991853
INFO: Iteration : 8, log likelihood : 2.991853
INFO: Iteration : 9, log likelihood : 2.991853
INFO: Iteration : 10, log likelihood : 2.991853
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.991853, Best log likelihood : 2.991853
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	

In [28]:
print(full_full_gllim.getParamB())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(full_full_gllim.getParamB())
# print(full_full_gllim.getParamSigma())

[[ 0.714681    0.81996818  0.80835346  0.12091032  0.86145835]
 [ 0.5122028   0.37198421  0.39274424  0.37303167  0.85310986]
 [ 0.85717997  0.55746484  0.78561817  1.05889949  0.94681903]
 [ 0.6630596   0.68076327  0.93906584  1.41288414 -1.4165929 ]
 [ 0.74759815 -0.31084578  0.6878273   0.51472693  1.29792477]
 [ 0.45248892  1.57694393  0.73900279  0.54919125  0.5200357 ]
 [ 0.43725492 -0.09718928 -0.03704346  0.83185509  1.55299883]
 [ 0.3634996   0.12174082  1.30622025 -0.55182549  1.09054384]
 [ 1.46178013  1.45543692  1.29972718  1.05529228  0.03889687]
 [ 0.30545515  0.6656632   0.24815184  0.07852961  1.12009649]
 [ 0.25021667 -0.32215709  0.57544037  0.92929945  1.68236119]
 [-0.36854636 -0.29812273  1.24434498  0.20316444  0.90242396]
 [ 0.18026551  0.53226056  0.54118019  0.71370559  0.13178548]
 [ 0.99554023  0.46201249  0.11187056  0.8162359   0.68473938]
 [ 0.27665585  0.26010011  0.12585639  1.18782452  0.75260541]
 [-0.43187942  0.39193903  0.55870947  1.01132238  1.78

#### Initialize + train GLLiM full/full from scratch

In [29]:
new_full_full_gllim = lib.GLLiM(K, D, L, 'full', 'full', n_hidden_variables)
print(new_full_full_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
new_full_full_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

print(new_full_full_gllim.getParamPi())
new_full_full_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_full_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'full'.

INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : 2.994533
INFO: Iteration : 2, log likelihood : 2.986467
INFO: Iteration : 3, log likelihood : 2.990063
INFO: Iteration : 4, log likelihood : 2.991853
INFO: Iteration : 5, log likelihood : 2.991853
INFO: Iteration : 6, log likelihood : 2.991853
INFO: Iteration : 7, log likelihood : 2.991853
INFO: Iteration : 8, log likelihood : 2.991853
INFO: Iteration : 9, log likelihood : 2.991853
INFO: Iteration : 10, log likelihood : 2.991853
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : 2.991853, Best log

## GLLM training : EM estimator : full/diag

In [30]:
L, D, K, N = 6, 30, 5, 4
new_theta = lib.GLLiMParameters(K,D,L, "full", "diag")

Gamma = np.random.rand(K,L,L)
Sigma = np.ones((K,D)) + np.random.rand(K,D) * 0.1
for k in range(K):
    Gamma[k,:,:] += np.eye(L) * 0.1
    Gamma[k,:,:] = np.dot(Gamma[k,:,:], Gamma[k,:,:].T) * 0.001
    # Sigma[k,:,:] += np.eye(D) * 0.1
    # Sigma[k,:,:] = np.dot(Sigma[k,:,:], Sigma[k,:,:].T) * 0.001
new_theta.Pi = np.ones(K) * 1 / K
new_theta.A = np.random.rand(D, L, K) * 0.3
new_theta.C = np.random.rand(L, K) * 0.2
new_theta.Gamma = Gamma
new_theta.B = np.random.rand(D, K) * 0.5
new_theta.Sigma = Sigma

X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

In [31]:
diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
diag_gllim.setParams(new_theta)

INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.


In [32]:
print(new_theta.Pi)
print(diag_gllim.getParamPi())
print(diag_gllim.getParamGamma())
print(new_theta.Gamma)

[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]
[[[0.00272543 0.00217679 0.00230063 0.00163464 0.00264453 0.00182747]
  [0.00217679 0.00270405 0.00192291 0.00178429 0.00277795 0.00233516]
  [0.00230063 0.00192291 0.00225143 0.00137849 0.00212177 0.00153386]
  [0.00163464 0.00178429 0.00137849 0.00167397 0.00197135 0.00173288]
  [0.00264453 0.00277795 0.00212177 0.00197135 0.0031959  0.00238185]
  [0.00182747 0.00233516 0.00153386 0.00173288 0.00238185 0.00238914]]

 [[0.00252435 0.00202222 0.00134014 0.00135086 0.00142447 0.00132459]
  [0.00202222 0.00289874 0.00147992 0.00215252 0.00134295 0.00157775]
  [0.00134014 0.00147992 0.00100437 0.00108681 0.00096631 0.00095618]
  [0.00135086 0.00215252 0.00108681 0.00172413 0.00086411 0.00130717]
  [0.00142447 0.00134295 0.00096631 0.00086411 0.00131842 0.00081429]
  [0.00132459 0.00157775 0.00095618 0.00130717 0.00081429 0.00164744]]

 [[0.00250311 0.00198818 0.00299345 0.00179442 0.00151354 0.00250042]
  [0.00198818 0.0018463  0.00227224 0.

In [33]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 3
seed = 12345
verbose = 1
diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(3)
print(diag_gllim.getParamPi())

[[0.2 0.2 0.2 0.2 0.2]]
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.245573
INFO: Iteration : 2, log likelihood : -0.245573
INFO: Iteration : 3, log likelihood : -0.245573
INFO: Iteration : 4, log likelihood : -0.245573
INFO: Iteration : 5, log likelihood : -0.245573
INFO: Iteration : 6, log likelihood : -0.245573
INFO: Iteration : 7, log likelihood : -0.245573
INFO: Iteration : 8, log likelihood : -0.245573
INFO: Iteration : 9, log likelihood : -0.245573
INFO: Iteration : 10, log likelihood : -0.245573
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.245573, Best log likelihood : -0.245573
INFO: Initialisation : 2
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM m

In [34]:
print(diag_gllim.getParamPi())
# x_gen_T = np.array(x_gen.T)
# y_gen_T = np.array(y_gen.T)
diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, 0)
print(diag_gllim.getParamPi())

[[0.2106097  0.2003391  0.22265643 0.19872482 0.16766996]]
[[0.2106097  0.2003391  0.22265643 0.19872482 0.16766996]]


#### Initialize + train GLLiM full/diag from scratch

In [35]:
new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag', n_hidden_variables)
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 30, 1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0.]]INFO: GLLiM Parameters initialized

INFO: GLLiM dimensions are (L=6, D=30, K=5)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.
INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -0.245573
INFO: Iteration : 2, log likelihood : -0.245573
INFO: Iteration : 3, log likelihood : -0.245573
INFO: Iteration : 4, log likelihood : -0.245573
INFO: Iteration : 5, log likelihood : -0.245573
INFO: Iteration : 6, log likelihood : -0.245573
INFO: Iteration : 7, log likelihood : -0.245573
INFO: Iteration : 8, log likelihood : -0.245573
INFO: Iteration : 9, log likelihood : -0.245573
INFO: Iteration : 10, log likelihood : -0.245573
INFO: Finish GLLiM-EM Training
INFO: 	Current log likelihood : -0.24557

In [36]:
import os
import newkernelo as lib
import numpy as np
import time
import logging
logging.getLogger().setLevel(logging.INFO)
L, D, K, N = 6, 30, 50, 4
X_gen = np.random.rand(L,N)
Y_gen = np.random.rand(D,N)

new_full_diag_gllim = lib.GLLiM(K, D, L, 'full', 'diag')
print(new_full_diag_gllim.getParamPi())
gllim_em_iteration = 10
gllim_em_floor = 1e-12
gmm_kmeans_iteration = 5
gmm_em_iteration = 12
gmm_floor = 1e-12
nb_experiences = 1
seed = 12345
verbose = 1
new_full_diag_gllim.initialize(X_gen, Y_gen, gllim_em_iteration, gllim_em_floor, gmm_kmeans_iteration, gmm_em_iteration, gmm_floor, nb_experiences, seed, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

print(new_full_diag_gllim.getParamPi())
new_full_diag_gllim.train(X_gen, Y_gen, 100, -1e-3, 1e-12, verbose)
time.sleep(1)
print(new_full_diag_gllim.getParamPi())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]INFO: GLLiM Parameters initialized
INFO: GLLiM dimensions are (L=6, D=30, K=50)
INFO: GLLiM constraints are :
	gamma_type = 'full',
	sigma_type = 'diag'.

INFO: Start Initialization
INFO: Initialisation : 1
INFO: 	Generate GMM means
INFO: 	Generate GMM covariance matrices
INFO: 	Train the GMM model
INFO: 	Compute Initial theta vector of the GLLiM model from GMM
INFO: 	Train the initial GLLiM model
INFO: Start GLLiM-EM Training
INFO: Iteration : 1, log likelihood : -2.549154
INFO: Iteration : 2, log likelihood : -2.549155
INFO: Iteration : 3, log likelihood : -2.549155
INFO: Iteration : 4, log likelihood : -2.549155
INFO: Iteration : 5, log likelihood : -2.549155
INFO: Iteration : 6, log likelihood : -2.549155
INFO: Iteration : 7, log likelihood : -2.549155
INFO: Iteration : 8, log likelihood : -2.549155
INFO: Iteration : 9, log lik

In [37]:
import os
os.system("")

print("\033[33mtest")
print("\033[33mtest")
print("\033[33m test\rTEST")
print("\033[34m  BLABLABLA")
print("\033[34m  BLA\033[35mBLABLA \r                                        \r\033[2Km blabla")
print("YOU CAN'T SEE ME\033[2K\rhello")

test
test
TESTm test
  BLABLABLA
m blabla                            
helloAN'T SEE ME
